- delete-user-data/extension.yaml
- firestore-bigquery-export/extension.yaml
- firestore-send-email/extension.yaml
- firestore-shorten-urls-bitly/extension.yaml
- firestore-translate-text/extension.yaml
- fix broken link to functions location page in firebase.google.com
- make link to top of page rather than to a section anchor
- add missing info about how to select a location
> fix broken link to functions location page in FGC

- storage-resize-images/extension.yaml
The parameter RESIZED_IMAGES_PATH does not need this link to the /products page; it should be on the IMG_SIZES param as this is the param that needs more in-depth explanation for proper configuration.
> [storage-resize-images] move "how param works" link to IMG_SIZES parameter

- delete-user-data/extension.yaml
This parameter is only applicable for those extensions that have a configured value for the FIRESTORE_PATHS parameter.
> add note to FIRESTORE_DELETE_MODE about applicability

- firestore-bigquery-export/scripts/import/package.json
- firestore-bigquery-export/scripts/import/src/index.ts
This change addresses https://github.com/firebase/extensions/issues/33.
> [firestore-bigquery-export] fix import script document name format

- firestore-counter/POSTINSTALL.md
Issue #21 
To POSTINSTALL file:
- Added clarification that subcollections aren't retained after summation
- Broke section out into steps of the process
> [firestore-counter] add clarification that subcollections aren't retained (POSTINSTALL)

- firestore-translate-text/extension.yaml
- firestore-translate-text/functions/src/config.ts
- firestore-translate-text/functions/src/index.ts
This PR should:
- Change the regex validation of the `languages` field to accept a single language list;
- Use a `Set` so that the extension doesn't translate to the same language more than once;
- Fix #43
> [firestore-translate-text] allow single language list

- delete-user-data/functions/lib/index.js
- delete-user-data/functions/src/index.ts
- firestore-send-email/functions/lib/index.js
- firestore-send-email/functions/src/index.ts
- firestore-shorten-urls-bitly/functions/lib/index.js
- firestore-shorten-urls-bitly/functions/src/index.ts
- firestore-translate-text/functions/lib/index.js
- firestore-translate-text/functions/src/index.ts
This PR introduces transaction based writes/deletes for extensions using Firestore, as discussed. 
Related PR: https://github.com/firebase/extensions/issues/48
> Migrate to Firestore transactions for writes

- firestore-bigquery-export/scripts/gen-schema-view/package.json
Right now the contents of the package `@firebaseextensions/fs-bq-schema-views` includes everything in `lib/`. We should only include things that aren't in `lib/test`.
> [fs-bq-export] omit test files from npm package contents

- auth-mailchimp-sync/extension.yaml
- auth-mailchimp-sync/package.json
- delete-user-data/extension.yaml
- delete-user-data/package.json
- exts-test-data/package.json
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/package.json
- firestore-counter/extension.yaml
- firestore-counter/package.json
- firestore-send-email/extension.yaml
- firestore-send-email/package.json
- firestore-shorten-urls-bitly/extension.yaml
- firestore-shorten-urls-bitly/package.json
- firestore-translate-text/extension.yaml
- firestore-translate-text/package.json
- rtdb-limit-child-nodes/extension.yaml
- rtdb-limit-child-nodes/package.json
- storage-resize-images/package.json
- Revise release note url for all extensions to point to Github releases page
- Remove version number from all package.jsons, since they are not used for anything, and it is a burden to keep them in sync with the versions in extension.yaml
- Add "private:true" to package.json so that npm will not complain about the lack of a version number in package.json
> Update release notes URL and delete versions in package.json

- .github/CODEOWNERS
Small PR to setup an initial GitHub [`CODEOWNERS`](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) file.
Code owners are automatically requested for review when someone opens a pull request that modifies code that they own. Code owners are not automatically requested to review draft pull requests. 
I've added the following rules for now;
- when any markdown (*.md) file is modified, request review from @rachelsaunders
- when any `package.json` or `lerna.json` file is modified, request review from myself and @Ehesp 
- when any of the new testing files/setup are modified, request review from myself and @Ehesp 
Hope these initial ones are ok? I can add more specific to each extension if required - let me know :)
> chore(*): Initial setup of CODEOWNERS file (automatic review assignments)

- storage-resize-images/README.md
- storage-resize-images/extension.yaml
Rationale: this API is actually auto-enabled for all new projects, so the extension does not need to specifically enable it.
> [storage-resize-images] Remove storage-component.googleapis.com from API list

- storage-resize-images/README.md
- storage-resize-images/extension.yaml
Reverts firebase/extensions#95
Reverting this, because as it stands today. The API will actually get disabled during the update of the extension, which is not a desired behavior. There's a backend fix for this that's in progress. After that's done, this can be re-merged.
> Revert "[storage-resize-images] Remove storage-component.googleapis.com from API list"

- firestore-bigquery-export/PREINSTALL.md
[This Stack Overflow post](https://stackoverflow.com/questions/58807763/when-using-firebase-extension-export-to-bigquery-is-the-export-free-or-is-it-c) asked a good clarifying question about BigQuery billing, so I added the information to the preinstall.
> docs(firestore-bigquery-export): clarify BigQuery billing

- firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md
Using lowercase "import" will give zero results since the value of the `operation` field is capitalized in rows written by the script.
> docs(firestore-bigquery-export) Capitalize "IMPORT" in example query

- .prettierignore
- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/tsconfig.json
- firestore-bigquery-export/functions/package.json
- firestore-bigquery-export/scripts/gen-schema-view/tsconfig.json
- firestore-bigquery-export/scripts/import/package.json
- firestore-bigquery-export/scripts/import/tsconfig.json
https://github.com/firebase/extensions/issues/101 identifies the possibility that the raw change log may contain duplicate rows with matching eventIds. This is due to the at-least-once nature of cloud function execution. One potential safeguard against this is to use the function's eventId as a BigQuery streaming insert `insertId`. This will give BigQuery streaming works the chance to deduplicate redundant rows coming from repeated Cloud function executions occurring within a couple of minutes of one another [1]. This should probably cover most instances of this issue. 
I've stress tested mirroring around 500K document changes to a collection and compared the number of rows in the raw changelog to the number of distinct event_ids and found them to be equal. This indicates that the fix …
> fix(firestore-bigquery-export): fix occasional duplicate entries in BigQuery

- firestore-translate-text/extension.yaml
For firestore-translate-text,the param LOCATION should be immutable, and not LANGUAGES.
> make LOCATION immutable, LANGUAGES should be mutable

- firestore-bigquery-export/scripts/import/src/index.ts
changing colon to underscore in the cursor position file name - for supporting windows environment execution
Error when trying to import from windows CMD:
Importing data from Cloud Firestore Collection: users, to BigQuery Dataset: firestore_export, Table: users_raw_changelogBigQuery dataset already exists: firestore_export
BigQuery table with name users_raw_changelog already exists in dataset firestore_export!
View with id users_raw_latest already exists in dataset firestore_export.
Inserting 300 row(s) of data into BigQuery
Inserted 300 row(s) of data into BigQuery
Error importing Collection to BigQuery: Error: ENOENT: no such file or directory, open 'C:\Users\Chen\AppData\Roaming\npm-cache\_npx\3232\node_modules\@firebaseextensions\fs-bq-import-collection\lib\from-users-to-<project_name> …
> fix(firestore-bigquery-export) Fix file name issue in import script for Windows

- firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md
The BigQuery import script requires Application Default Credentials to run. Adding a step to the instructions to document that.
[PREVIEW HERE](https://github.com/firebase/extensions/blob/bq-script-auth/firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md#run-the-script)
> Add auth step to bigquery import script instructions

- storage-resize-images/extension.yaml
Handles #27 & allows for #18
Currently the rules assume the bucket name is always `x.x.x`, whereas it can actually be anything with letters, numbers, dashes, dots, underscores.
This only checks for characters, it doesn't validate the storage bucket actually exists.
> fix(storage-resize-images) relax bucket naming rules

- storage-resize-images/functions/lib/index.js
- storage-resize-images/functions/src/index.ts
Fixes https://github.com/firebase/extensions/issues/130
When images are uploaded to storage, depending on the tool used (e.g. Console vs gsutils vs SDK), the metadata object is not always created. This quick fix ensures an empty object is always available when resizing.
> fix(storage-resize-images): Fix "TypeError: Cannot set property 'resizedImage' of undefined" by ensuring metadata is always available

- storage-resize-images/__tests__/extractFileNameWithoutExtension.ts
- storage-resize-images/functions/lib/index.js
- storage-resize-images/functions/lib/util.js
- storage-resize-images/functions/src/index.ts
- storage-resize-images/functions/src/util.ts
I'm not sure if it is the expected behavior or not, and if so, please disregard this PR.
As someone has pointed out in [this comment](https://github.com/firebase/extensions/issues/130#issuecomment-564425978), when a user uploads an image to the storage with a ref name **without** an extension, resized image's name gets to be trimmed like `_200x200`.
Below is a sample code that reproduces this.
```typescript
const storageRef = firebase.storage().ref('RANDOM_PATH')
const folderRef = storageRef.child('my_beautiful_cat')
await folderRef.put(e.target.files[0]) // got this from File API
```
It seems like the problem is happening where it [extracts the file name without extension](https://github.com/firebase/extensions/blob/next/storage-resize-images/functions/src/index.ts#L66). 
The current …
> fix(storage-resize-images): fix bug where name of resized file was missing original name if there was no file extension

- auth-mailchimp-sync/CHANGELOG.md
- auth-mailchimp-sync/extension.yaml
- delete-user-data/CHANGELOG.md
- delete-user-data/extension.yaml
- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/extension.yaml
- firestore-counter/CHANGELOG.md
- firestore-counter/extension.yaml
- firestore-send-email/CHANGELOG.md
- firestore-send-email/extension.yaml
- firestore-shorten-urls-bitly/CHANGELOG.md
- firestore-shorten-urls-bitly/extension.yaml
- firestore-translate-text/CHANGELOG.md
- firestore-translate-text/extension.yaml
- rtdb-limit-child-nodes/CHANGELOG.md
- rtdb-limit-child-nodes/extension.yaml
- storage-resize-images/CHANGELOG.md
- storage-resize-images/extension.yaml
Changes the release notes URL to point to specific extension changelog files, as discussed.
- auth-mailchimp-sync & rtdb-limit-child-nodes did not have a `CHANGELOG.md`, so I creates a stub so the URL doesn't 404. Is this ok being blank?
- Each link points to `master` - assuming this is ok?
> chore(*): update release notes URLs

- delete-user-data/extension.yaml
- delete-user-data/functions/lib/index.js
- delete-user-data/functions/src/index.ts
Implements #148
`bucket.file(x)` only allows deleting specific files, not directories. This change uses `deleteFiles` with a prefix arg to delete both files and directories.
```
-- my-bucket
-- 123
-- foo.jpg
-- bar.jpg
-- 567.png
```
Given the structure above, the user could enter the following into the setup args to delete both `foo.jpg` & `bar.jpg` files:
`my-bucket/{UID}` (UID = 123)
To delete a single file, they'd do the usual:
`my-bucket/{UID}.png` (UID = 567)
> feat(delete-user-data): allow deleting directories & files

- firestore-counter/functions/src/worker.ts
Firestore transactions perform best for up to 100 documents.
Fixes https://github.com/firebase/extensions/issues/64
> Lower SHARDS_LIMIT to 100.

- auth-mailchimp-sync/extension.yaml
- delete-user-data/extension.yaml
- firestore-bigquery-export/extension.yaml
- firestore-counter/extension.yaml
- firestore-send-email/extension.yaml
- firestore-shorten-urls-bitly/extension.yaml
- firestore-translate-text/extension.yaml
- rtdb-limit-child-nodes/extension.yaml
- storage-resize-images/extension.yaml
Clarifying the parameter LOCATION in _all_ extension.yaml files. For firestore-bigquery-export, also clarified that the default location of the BigQuery dataset is `us-central1`.
Issue #96
> [all] clarify label & description of LOCATION param; note for default BigQuery location

- firestore-counter/POSTINSTALL.md
- firestore-counter/PREINSTALL.md
Treat the [TypeScript client](https://github.com/firebase/extensions/tree/master/firestore-counter/clients/web/src/index.ts) as a canonical sample implementation to be used by anyone looking to implement a client for `firestore-counter`.
> docs(firestore-counter): change "Counter SDK" to "Client Sample"

- firestore-shorten-urls-bitly/functions/lib/abstract-shortener.js
- firestore-shorten-urls-bitly/functions/lib/index.js
- firestore-shorten-urls-bitly/functions/lib/logs.js
- firestore-shorten-urls-bitly/functions/src/index.ts
- firestore-shorten-urls-bitly/package.json
See #170 for more details. This directly connects with the v4 API via a POST request.
> fix(firestore-shorten-urls-bitly) migrate to v4 api #170

- firestore-send-email/functions/src/templates.ts
When using the `templates` option for the send email extension, Handlebars by default will HTML escape all text. This change disables that escaping for plain text fields like `subject` and `text`, so that a symbol like `&` does not render as `&amp;` in a subject line, for example (as is current behavior).
> Disable HTML escaping for text and subject fields

- firestore-send-email/functions/src/templates.ts
Reverts firebase/extensions#169
since it was accidentally merged to master
> Revert "Disable HTML escaping for text and subject fields"

- firestore-send-email/functions/src/templates.ts
Redo of https://github.com/firebase/extensions/pull/169
> fix(firestore-send-email) Disable HTML escaping for text and subject fields

- firestore-shorten-urls-bitly/functions/lib/index.js
- firestore-shorten-urls-bitly/functions/src/index.ts
Bitly requests now appear to require a `Content-Type` to work. If none set, the request fails with a 406 error.
This PR resolves this issue.
> fix(bitly-shortener): Fix 406 HTTP error code from Bit.ly API due to "Content-Type" not being set. 

- auth-mailchimp-sync/package-lock.json
- delete-user-data/package-lock.json
- firestore-bigquery-export/package-lock.json
- firestore-send-email/package-lock.json
- firestore-shorten-urls-bitly/package-lock.json
- firestore-translate-text/package-lock.json
- rtdb-limit-child-nodes/package-lock.json
- storage-resize-images/package-lock.json
addresses #35
Ran audit on extensions, upgraded vulnerable packages. The only extension that hasn't been upgraded is `firestore-shorten-urls-bitly`. There appeared to be problems with its functionality. Need to have another look at `firestore-shorten-urls-bitly`
> fix(*): upgrade vulnerable node modules

- firestore-send-email/extension.yaml
This PR resolves this feature request #167.
> feat(firestore-send-email): update "Default FROM address" param to allow name to be added

- storage-resize-images/POSTINSTALL.md
- storage-resize-images/functions/lib/index.js
- storage-resize-images/functions/lib/logs.js
- storage-resize-images/functions/src/index.ts
- storage-resize-images/functions/src/logs.ts
- Fix: Files are not always uploaded with a default content type (e.g. gsutils).
- Docs: File validation is unknown to the user. Added a note which indicates a file must have a content type, and one which starts with the `image/` prefix.
Fixes https://github.com/firebase/extensions/issues/175
> fix(storage-resize-images): ensure content type is always available

- firestore-bigquery-export/scripts/gen-schema-view/src/udf.ts
if you need to run gen-schema-views multiple times, you get an error "function already exists", adding "IF NOT EXISTS" to safely run script multiple times
> fix(firestore-bigquery-export-gen-schema-view): create udfs if not exists

- firestore-send-email/extension.yaml
Remove Friendly Firebaser <foobar@example.com> example in param description. The carats (`<`, `>`) cause parsing issues.
> firestore-send-email param description edit

- firestore-translate-text/functions/lib/logs/messages.js
- firestore-translate-text/functions/src/logs/messages.ts
From chatting with Rachel, we've realized that the words 'configuration' and 'config' are overloaded in the context of extensions. Since these are actually parameter values, I think this will be slightly clearer.
> refactor(firestore-translate-text): clarify log message

- firestore-shorten-urls-bitly/PREINSTALL.md
Bitly's company name is "Bitly", not "bit.ly" or "Bit.ly".  The URL that they generate is "bit.ly".
> docs(firestore-shorten-urls-bitly): changed Bit.ly to Bitly in PREINSTALL file

- firestore-send-email/extension.yaml
As discussed via email, I've placed backticks around the email address which negates the console from removing the angled brackets in the documentation.
> docs(firestore-send-email): Backtick around angled brackets within extension.yaml

- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/index.ts
- firestore-bigquery-export/scripts/gen-schema-view/.gitignore
- firestore-bigquery-export/scripts/gen-schema-view/package.json
fixes #250 
- The latest commit for the `gen-schema-view` uses the `firestore-bigquery-change-tracker` package  script which is not specified in the `package.json`.
fixes #196
- The `RawChangelogViewSchema ` was not exported out of the `firestore-bigquery-change-tracker` package. This caused the `fields` property to be `undefined` at this [point](https://github.com/firebase/extensions/blob/d4c56a510094b19c0809d24f335b6c39ecc104de/firestore-bigquery-export/scripts/gen-schema-view/src/schema.ts#L193) in the code.
Here's a screenshot of the `gen-schema-view` script working again:
Please note that the `gen-schema-view` package will still not work until this PR has been merged and the `firestore-bigquery-change-tracker` & `gen-schema-view` packages have been published again.
> fix(firestore-bigquery-export): add package & update exports

- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
- firestore-bigquery-export/package.json
- firestore-bigquery-export/scripts/gen-schema-view/package.json
Fixes #265
The previous fix stopped functioning after dependancy updates - there are two versions of the `@google/firestore` Node.js module being used due to the BigQuery scripts using an older version of `firebase-admin` vs the version `firebase-functions` uses -  this meant that `instanceof` checks would evaluate to false as there were two instances (or versions) of the class in use
Adding document with reference to Firestore:
BigQuery row in table:
> fix(firestore-bigquery-export): fix bug where modules were not sharing the same Firestore DocumentReference (issue #265)

- storage-resize-images/functions/lib/index.js
- storage-resize-images/package.json
This is the last `sharp` version to [support](https://sharp.pixelplumbing.com/changelog#v0240---16supthsup-january-2020) Node.js 8. It appears the Cloud Functions switch to using Yarn package manager throws an error when installing `sharp` `v0.24` or higher as it requires Node.js >=10
Here are the logs of an image being resized:
Here are the images resized in the storage bucket:
> fix(storage-resize-image): fix Sharp version to v0.23 to preserve compatibility with Node 8

- .github/workflows/release.yml
- .github/workflows/scripts/release.sh
This GitHub action creates (or updates) the latest release for each extension, triggered only on push to **master** only.
- Finds all Extensions (directories containing `extension.yaml` file)
- For each Extension:
- Read current Extension version from yaml file
- Read changes for the version from the extensions `CHANGELOG.md`
- Query GitHub API for `firebase/extensions` repo and checks if release exists already:
- EXISTS: update it release body (allows changes made in `CHANGELOG.md` after a release to be automatically reflected in the relevant release)
- DOES_NOT_EXIST: create a new GitHub release & tag
Notes:
- `GITHUB_TOKEN` secret automatically [provided by GitHub actions](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#example- …
> chore: initial GitHub releases action

- .huskyrc
- package.json
Removes the pre-commit hook that lints commit messages - no longer required as we're squashing commits.
> chore: remove husky commit hook

- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
- firestore-bigquery-export/package.json
fixes #284 
Test every type (excluding `Blob` type) and nesting within object & array:
Firebase Console logs:
Created Record in BigQuery table:
> fix(firestore-bigquery-export): fix "TypeError: Cannot read property 'constructor' of null" (Issue #284)

- storage-resize-images/functions/lib/index.js
- storage-resize-images/functions/src/index.ts
fixes #286
Sharp persists images. If the same name & extension are used, it will use the image persisted in cache. 
This PR clears cache to ensure that the latest image retrieved from the bucket is resized.
correct images being resized to 300x300 pixels.
> fix(storage-resize-images): clear cache so that image names can be reused (Issue #286)

- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
This PR filters out `Blob` (`Buffer`) data types from being stored as strings in Big Query:
Adding data:
Firebase Console logs:
Row in BigQuery table:
> fix(firestore-bigquery-export): filter out blobs data from being mirrored into BigQuery

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/extension.yaml
- storage-resize-images/CHANGELOG.md
- storage-resize-images/extension.yaml
For storage-resize-images and firestore-bigquery-export.
> 5/7/2020 Release: bump patch version rather than minor version

- storage-resize-images/functions/lib/index.js
- storage-resize-images/functions/src/index.ts
fixes #290
Shows the image being displayed correctly using the image's EXIF orientation property in the Mac's image viewer:
Shows the same image displayed in VScode which does not use the EXIF data orientation property:
This shows how the resized image is displayed in the firebase console (The resized image loses EXIF data) without this PR change:
This shows the resized image being displayed correctly. It doesn't have the EXIF data, but it was rotated at the time of resizing using the EXIF data orientation property:
> fix(storage-resize-images): fix bug where resized image did not keep orientation of original image (Issue #290)

- firestore-bigquery-export/scripts/gen-schema-view/package.json
- firestore-bigquery-export/scripts/gen-schema-view/src/index.ts
- firestore-bigquery-export/scripts/gen-schema-view/src/schema.ts
- firestore-bigquery-export/scripts/gen-schema-view/src/snapshot.ts
fixes #295
fix: Changing JSON SQL function to `JSON_EXTRACT_SCALAR` as per [docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions).
Notes
- fixed `timestamp` type to extract `seconds` & `nanoseconds` from dataset tables. It currently returns `null`.
- Made variable names slightly more semantic.
- `initializeSchemaViewResources ` returns `void` as no return value is expected.
- bumped `@google-cloud/bigquery` to "^4.7.0". Currently two major versions out of sync.
- bumped `gen-schema-view` script to version `0.1.8`
This is the schema file I used to test the script:
This shows the `stringType` returning a single set of double quotes around a string property. It also shows the `timestamp` type returning the `seconds` &  `nanoseconds` properties like the Firestore …
> fix(gen-schema-view): double quotes around strings & return timestamp type

- firestore-bigquery-export/scripts/gen-schema-view/package.json
- firestore-bigquery-export/scripts/gen-schema-view/src/schema.ts
fixes #247
Screenshot of successfully generating schema view without error
Screenshot of view in Big Query updated with column name successfully changed to `colon_colon`.
> fix(firestore-bigquery-export): clean column names for generating schema views

- firestore-bigquery-export/scripts/gen-schema-view/package.json
- firestore-bigquery-export/scripts/gen-schema-view/src/schema.ts
- firestore-bigquery-export/scripts/gen-schema-view/src/udf.ts
fixes #318, fixes #324.
- The timestamp and geopoint objects require a `JSON_EXTRACT` as pointed out by @caesarivs.
- The geopoint longitude & latitude extracts are switched as per the [documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/geography_functions#st_geogpoint) provided by @vpetlu. 
This shows the timestamp and the geopoint correctly extracted in the changelog view.
> fix(firestore-bigquery-export): fix bug where timestamp values are not correctly parsed (Issue #324).

- storage-resize-images/functions/lib/index.js
- storage-resize-images/functions/src/index.ts
Fix #337
From the [sharp docs](https://sharp.pixelplumbing.com/api-resize#parameters):
`options.withoutEnlargement` do not enlarge if the width or height are already less than the specified dimensions, equivalent to GraphicsMagick's `>` geometry option. (optional, default `false`)
> fix(storage-resize-images): stop images from getting enlarged if they were smaller than max width and height (Issue #337).

- storage-resize-images/POSTINSTALL.md
- storage-resize-images/PREINSTALL.md
- storage-resize-images/README.md
- storage-resize-images/functions/lib/index.js
- storage-resize-images/functions/src/index.ts
- storage-resize-images/package.json
As discussed in https://github.com/firebase/extensions/issues/323, image download tokens are being copied which is problematic. This PR updates the flow to check if a download token exists on the original image, and if so, generates a fresh token on the image being resized.
> fix(storage-resize-images): generate fresh token for resized image (Issue #323).

- firestore-bigquery-export/functions/lib/index.js
- firestore-bigquery-export/functions/lib/util.js
- firestore-bigquery-export/functions/src/index.ts
- firestore-bigquery-export/functions/src/util.ts
Closed down PR #373 to base of `next` branch.
- updates the changelog table and the snapshot latest view to have a `document_id` column.
- replaces this PR: #346 created by a Firebase Extension's user.
`latest` view with the column at the end containing the document id.
`changelog` table with the column at the end containing the document id.
> feat(firestore-bigquery-export): add document id column in changelog table and snapshot view

- firestore-bigquery-export/scripts/import/src/index.ts
After running `import` script the `document_id` column appears in the view:
- `document_id` column for the `firestore-bigquery-export` `import` script.
> feat(firestore-bigquery-export): import script imports document id

- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/snapshot.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/sql/latestConsistentSnapshot.txt
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/sql/latestConsistentSnapshotNoGroupBy.txt
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/schema.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/snapshot.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/tracker.ts
- firestore-bigquery-export/scripts/import/src/index.ts
-  `document_id` implementation for `firestore-bigquery-change-tracker` which the `firestore-bigquery-export` extension depends upon.
> feat(firestore-bigquery-export): record document id of changes tracked by firestore-bigquery-change-tracker package

- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/sql/latestConsistentSnapshot.txt
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/sql/latestConsistentSnapshotNoGroupBy.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/arraysNestedInMapsSchema.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/emptyMapSchema.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/emptySchemaChangeLog.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/emptySchemaLatest.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/emptySchemaLatestFromView.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/fullSchemaChangeLog.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/fullSchemaLatest.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/fullSchemaLatestFromView.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/fullSchemaLatestLatestFromView.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/fullSchemaSquared.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/latestConsistentSnapshot.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/latestConsistentSnapshotNoGroupBy.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/nestedMapSchemaChangeLog.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/referenceSchema.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/schema.ts
- firestore-bigquery-export/scripts/gen-schema-view/src/snapshot.ts
- Creates a `document_id` column when using the `gen-schema-view` script.
Created a view with `document_id` column.
> feat(firestore-bigquery-export): create document id column when using gen-schema-view script

- firestore-bigquery-export/scripts/import/package.json
- firestore-bigquery-export/scripts/import/src/index.ts
This PR resolves this feature request #294 
I followed the same pattern as `gen-schema-view`
The output of `--help` is:
```
Usage: fs-bq-import-collection [options]
Options:
--non-interactive                                      Parse all input from command line flags instead of prompting the
caller. (default: false)
-P, --project <project>                                Firebase Project ID for project containing the Cloud Firestore
database.
-s, --source-collection-path <source-collection-path>  The path of the the Cloud Firestore Collection to import from.
(This may, or may not, be the same Collection for which you plan to
mirror changes.)
-d, --dataset <dataset>                                The ID of the BigQuery dataset to import to. (A dataset will be
created if it doesn't already …
```
> feat(fs-bq-import-collection): Support command line arguments

- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/package.json
firestore-bigquery-export needs to be version-bumped, so that consumers who have installed instances can be notified via Console UI to update.
> Bump firestore-bigquery-export version

- firestore-bigquery-export/extension.yaml
fixes https://github.com/firebase/extensions/issues/410
- `firestore-bigquery-export` was the only extension without a regex for its Firestore collection path param.
Attempts at odd number of path segments:
> feat(firestore-bigquery-export): Add validation regex for collection path parameter.

- codecov.yml
Fix CI failures due to coverage issues by disabling patch status reporting, patch % = new code added & what % of that new code has got test coverage (which doesn't really work well with compiled code being committed). Overall project coverage % will still remain and be tracked.
Docs: https://docs.codecov.io/docs/commit-status#disabling-a-status
**Before:** (has patch check)
**After:** (no more patch check)
Additionally this lowers the overall repository coverage range to 35, down from 40, as its currently around 39% and causes PRs to fail as it's below the 40% threshold.
> chore: disable patch status coverage reporting

- firestore-translate-text/POSTINSTALL.md
fixes #447 
Update `POSTINSTALL.md` file with example of multiple field translations.
> docs(firestore-translate-text): multiple inputs

- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/arraysNestedInMapsSchema.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/emptySchemaLatestFromView.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/fullSchemaChangeLog.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/fullSchemaLatest.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/fullSchemaLatestFromView.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/fullSchemaLatestLatestFromView.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql/fullSchemaSquared.txt
- firestore-bigquery-export/scripts/gen-schema-view/src/schema.ts
- firestore-bigquery-export/scripts/gen-schema-view/src/snapshot.ts
fixes #298 
- Switched from a `CROSS JOIN` to a `LEFT JOIN` SQL query. 
- This PR only affects the `gen-schema-view` script.
The `LEFT JOIN` will not hide a row if an array in the table is empty:
As can be noted below, the rows for `Viva_Parker63@gmail.com` & `Laurence_Heaney65@hotmail.com` rows are missing when using a `CROSS JOIN`:
> fix(firestore-bigquery-export): update "gen-schema-view" script to not hide data rows

- .github/workflows/scripts/release.sh
Fixes an issue where if an extension does not have a `CHANGELOG.md` file the script would error and exit ([example](https://github.com/firebase/extensions/runs/1097667905#step:3:12)).
Additionally made the following changes (see individual commits):
- formatted the script
- removed temporary version skipping logic as it's now no longer required as each extension has since had a release.
Tested all 3 scenarios (release already exists, changelog could not be found, new release):
Testing releases can be seen here: https://github.com/invertase/extensions-release-testing/releases
> fix(release): use placeholder changelog entry when changelog file does not exist

- firestore-bigquery-export/guides/EXAMPLE_QUERIES.md
fixes #444 
Provide example of how to delete rows in the changelog table generated by the `firestore-bigquery-export` table
> docs(firestore-bigquery-export): delete query

- firestore-bigquery-export/firestore-bigquery-change-tracker/src/logs.ts
- firestore-bigquery-export/functions/big-query-table-test/install-script.js
- firestore-bigquery-export/functions/package.json
Downgrade `firebase-admin` in `firestore-bigquery-export` extension to stop it from breaking the tests. Some types have changed and may need to be updated, or the big query test script for inserting data will have to be changed, and the `not-in` query removed.
> chore(firestore-bigquery-export): revert firebase-admin dependency back to v8

- storage-resize-images/POSTINSTALL.md
fixes #530
documents setting content type explicitly and which content types are supported by `storage-resize-images` extension
> docs(storage-resize-images): explicit content type

- storage-resize-images/functions/lib/logs.js
- storage-resize-images/functions/src/logs.ts
`storage-resize-images` audit of cloud function logger. Partial resolution of #543.
Logs of successful resize:
> chore(storage-resize-images): use cloud function logger

- firestore-bigquery-export/functions/__tests__/__mocks__/console.ts
- firestore-bigquery-export/functions/__tests__/functions.test.ts
- firestore-bigquery-export/functions/lib/logs.js
- firestore-bigquery-export/functions/src/logs.ts
Updated `firestore-bigquery-export` extension to use `firebase-functions` logger as part of #543.
Hey @jhuleatt,  I haven't updated the `console.logs` in the BigQuery scripts as I wasn't sure it was necessary. Let me know if this is desirable and I will update.
> chore(firestore-bigquery-export): use firebase-functions logger

- firestore-send-email/functions/lib/logs.js
- firestore-send-email/functions/lib/templates.js
- firestore-send-email/functions/src/logs.ts
- firestore-send-email/functions/src/templates.ts
Updated `firestore-send-email` extension to use `firebase-functions` logger as part of #543.
Log of email successfully sent (I also received as expected):
> chore(firestore-send-email): use firebase-functions logger

- delete-user-data/functions/lib/config.js
- delete-user-data/functions/lib/index.js
- delete-user-data/functions/src/config.ts
- delete-user-data/functions/src/index.ts
fixes #531 
Here is a log of the `{DEFAULT}/testext/{UID}.jpg` being deleted:
I also spent some time trying to run the emulator for this extension. The cloud function emulator ran as expected, the auth emulator did not. I'll create an issue on the `firestore-tools` repository.
> fix(delete-user-data): storage bucket param

- firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md
- firestore-counter/POSTINSTALL.md
fixes #501
Make documentation a bit more explicit about how to use a `collectionGroup` query when backfilling data into your BigQuery table.
> docs(firestore-bigquery-export): collectionGroup import script documentation improvement

- codecov.yml
Coverage on some modules such as `firestore-send-email` are currently stopping updates in the repository. This fix removes the check on the CI to enable new fixes and features to be added.
> fix(*): Removed code coverage check on ci

- firestore-send-email/README.md
Updated documentation for recommended ports when sending emails.
Fixes #574
> docs(firestore-send-email): Updated documentation for recommended ports

- storage-resize-images/functions/lib/resize-image.js
- storage-resize-images/functions/src/resize-image.ts
fixes #544
Logs of image resize:
Image as it appears in the storage bucket with extension appended correctly:
> fix(storage-resize-images): capitalised file extensions

- firestore-bigquery-export/extension.yaml
fixes: https://github.com/firebase/extensions/issues/602
> feat(firestore-bigquery-export) Add us-central-1 as a dataset location option

- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/snapshot.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
- firestore-bigquery-export/functions/__tests__/__snapshots__/config.test.ts.snap
- firestore-bigquery-export/functions/lib/config.js
- firestore-bigquery-export/functions/lib/index.js
- firestore-bigquery-export/functions/src/config.ts
- firestore-bigquery-export/functions/src/index.ts
Fixes https://github.com/firebase/extensions/issues/316
1. Tested creating fresh time partitioned BigQuery tables without a problem
2. Tested "updating" the extension whilst pointing to existing non-partitioned BigQuery tables. 
The feature is backwards compatible. The BigQuery tracker package always checks if the table exists before setting the `timePartitioning` metadata for the raw changelog table and the latest view table. This also means the import script will not be affected as long as the table has already been created by the extension (which is the recommended way).
In future, we may also wish to update the `gen-schema-view` script to also allow time partitioning, but I suggest we wait for this to land and raise a separate PR.
> feat(firestore-bigquery-export): big query partitioned tables

- .github/workflows/test.yml
Recreating #613 off of next instead of master.
We noticed some conflicting settings in this repo:
Per gh action workflow config node{10,12} test do not run if the change only includes *.md file
Per gh repo setting, merge into next branch MUST include passing result of node{10,12} tests (https://github.com/firebase/extensions/settings/branch_protection_rules/12097847)
This makes the tests always run - we figured it was better to have a few 'wasted' actions than to make these not required or get in the habit of ignoring these checks.
> Stop ignoring .md files, so that all required checks are run

- storage-resize-images/extension.yaml
- storage-resize-images/functions/__tests__/util.test.ts
- storage-resize-images/functions/lib/util.js
- storage-resize-images/functions/src/util.ts
fixes #560
Allow wildcard notation for directory names.
Supplied path for images I want to be resized: `/users/*/pictures`
Unsuccessful upload to `/users/portraits/avatar`:
Uploaded successfully to `/users/profile`:
/pictures`:
Supplied paths for images I don't want to be resized: `/animals/*/cats,/animals/*/dogs/*/sleepy`
Unsuccessful upload to `/animals/fluffy/dogs/large/sleepy`:
Unsuccessful upload to `/animals/fluffy/cats/large/sleepy`:
Uploaded successfully to `/animals/fluffy/dogs/large/fast`:
> feat(storage-resize-images):wildcard in include/exclude paths

- firestore-bigquery-export/scripts/import/package.json
- firestore-bigquery-export/scripts/import/src/index.ts
fixes: https://github.com/firebase/extensions/issues/584
When using collections below the root collection of database, the `/`separating the collections  is interpreted as part of the temporary file path which is created. This has been updated to use `-` instead.
> fix(firestore-bigquery-export): Updated file naming for bq imports

- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-translate-text/PREINSTALL.md
- firestore-translate-text/README.md
- firestore-translate-text/extension.yaml
- firestore-translate-text/functions/package.json
- firestore-translate-text/functions/tsconfig.json
> chore(firestore-translate-text): migration to Node.js v14

- firestore-bigquery-export/PREINSTALL.md
- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/tsconfig.json
- firestore-bigquery-export/functions/package.json
- firestore-bigquery-export/functions/tsconfig.json
> chore(firestore-bigquery-export): migration to Node.js v14

- .gitignore
- firestore-counter/.gitignore
Removing package-lock.json from .gitignore, for a few reasons:
- Not having these committed caused a broken release of the bigquery extension a few weeks back 
- npms official help docs say that it is intended to be commited: https://github.com/npm/cli/blob/release-6.14.7/docs/content/configuring-npm/package-lock-json.md
- The Cloud Build code for node14 runs npm ci, which will not generate a new package-lock.json
I didn't go through and generate package-locks for each extension - I figure we can add these alongside normal PRs to each extension.
> chore: remove package-lock.json from .gitignore

- firestore-send-email/extension.yaml
Removed duplicate Warsaw location in `firestore-send-email`.
> fix(firestore-send-email) removed duplicate warsaw location

- .github/workflows/test.yml
Dropping Node.js v10 and adding v14 to the CI tests job.
cc @jhuleatt - the branch protection rules on the repo will need updating since `node.js_10_test` is marked as an expected CI status blocking merge - could add `node.js_14_test` in its place. Thanks!
> ci: drop Node.js v10 and add v14 to tests job

- .github/workflows/test.yml
- firestore-counter/POSTINSTALL.md
- firestore-counter/PREINSTALL.md
- firestore-counter/README.md
- firestore-counter/clients/node/index.js
- firestore-counter/clients/node/package.json
The firestore distributed counter SDK does not exist for backend services like Node.js (#28).
This PR aims to solve that by converting the web client Typescript implementation into Node.js.
> feat(firestore-counter): Add Node.js Admin SDK Implementation

- storage-resize-images/functions/package-lock.json
Update to match the latest node type changes.
Fixes: https://github.com/firebase/extensions/issues/781
See https://github.com/firebase/extensions/pull/779 also for related PR/changes.
> fix(storage-resize-images): update package lock file

- storage-resize-images/functions/lib/resize-image.js
- storage-resize-images/functions/src/resize-image.ts
fixes: #787
**Update Engine**
**Installed extension with settings**
**Successful result with logs**
> fix(delete-resize-images): tif fix

- storage-resize-images/functions/lib/resize-image.js
- storage-resize-images/functions/src/resize-image.ts
fixes: #755
I was able to recreate the issue and apply recommended setting to avoid the bug. I have checked the metadata of the photo and found that it was taken with Samsung phone. Sharp maintainers mentioned this solution in below topics:
[https://github.com/lovell/sharp/issues?q=VipsJpeg%3A+Invalid+SOS+parameters](https://github.com/lovell/sharp/issues?q=VipsJpeg%3A+Invalid+SOS+parameters)
Photo used to recreate the bug:
[https://gist.githubusercontent.com/mnaoumov/060166a995eb75666d95203a1d9f468b/raw/6a2b0f46422beb63a4aea4185463edbda96d04cb/5242.jpg](https://gist.githubusercontent.com/mnaoumov/060166a995eb75666d95203a1d9f468b/raw/6a2b0f46422beb63a4aea4185463edbda96d04cb/5242.jpg)
**Update Engine**
**Installed extension with settings**
**Successful result with logs**
> fix(storage-resize-images): fix samsung encoded jpg resizing

- .github/workflows/scripts/npm_publish.sh
The HTTP endpoint returns nothing so the NPM publish script fails.
> Use HTTPS to fetch from NPM registry.

- firestore-bigquery-export/scripts/import/src/index.ts
- firestore-bigquery-export/scripts/import/src/run.ts
- firestore-bigquery-export/scripts/import/src/worker.ts
fixes: #741
When using import script timestamp date is 1970-01-01 00:00:00 UTC and it should show the actual date of the import.
Show the actual timestamp date of import.
- fix new Date in index, run and worker
> fix(firestore-bigquery-export): import script date

- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/logs.ts
fixes: https://github.com/firebase/extensions/issues/869
> fix(firestore-bigquery-change-tracker): added additional checks on table creation

- firestore-bigquery-export/functions/package-lock.json
- firestore-bigquery-export/functions/package.json
PR to add version `v1.1.14` of the `firestore-bigquery-change-tracker` to the `firestore-bigquery-export` extension.
> chore(firestore-bigquery-export): upgraded extension to use firestore-change-tracker v1.1.14

- firestore-translate-text/functions/package-lock.json
- firestore-translate-text/functions/package.json
Installations currently fail as all `npm dependencies` must be available when using a `prepare` script to install an extension.
This update moves `rimraf` as a `devDependencies` to `dependencies` to fix the installation issue.
> fix(firestore-translate-text): updated dependencies for extension installation through prepare script

- firestore-bigquery-export/extension.yaml
Originally a BigQuery Project Id was allowed to be left as an optional field and would default to the current firebase project that the extension is running on.
With this field blank, documentation would show this as an `unspecified parameter`. This update ensures that a `project name` is always provided for the extension to synchronise data with and to always provide a `BigQuery Project Name` for the extensions documentation.
> fix(firestore-bigquery-export): updated the bq projectId to be required and to default as the current firebase project

- storage-resize-images/functions/src/resize-image.ts
Currently, if no OUTPUT_OPTIONS is provided then an error log is printed, even though this param is optional: 
This PR updates to first check if a value has actually been set.
> fix(storage-resize-images): check if the outputOptions param is undefined to prevent unnecessary error log

- firestore-send-email/functions/src/logs.ts
- firestore-send-email/functions/src/templates.ts
Currently, there is a logger inside the template loading forEach loop. It logs `loaded template {template-name}` message after each template loads.
Moved the logger outside the forEach and converted the message to `loaded templates {template,name,array}` to log the message only once.
fixes: #944
> fix(firestore-send-email): move log statement outside of forEach loop

- scripts/publish.sh
* changed `npm install` to `npm ci`
* introduced  extra flag to pass additional flag for the `firebase ext:dev:publish` call
* fixed error code handling
> Minor tweaks to the publish script

- storage-resize-images/functions/src/index.ts
Include the original image metadata object in the event.
Metadata object shape: https://firebase.google.com/docs/reference/functions/providers_storage.objectmetadata
fixes #1019
> feat(storage-resize-images): include original image data in events

- storage-resize-images/functions/src/logs.ts
`errorDeleting` is not exclusively called for temporary files. It is also called when the caller of `remoteFileDeleted` fails, so the current log message is inaccurate.
> Tweak "errorDeleting" wording

- storage-resize-images/functions/src/index.ts
- storage-resize-images/functions/src/resize-image.ts
- storage-resize-images/functions/src/util.ts
The previous code involved many assignments at the caller's level and a helper function; this PR removes the helper function and moves the assignments into the function body using a destructuring assignment.
I'm not sure about the variable names I chose, so please be opinionated if you'd like. I kept the old variable names where possible to minimize the diff size.
Looking forward to your thoughts.
> Simplify parsed path passing

- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/e2e.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/changeTracker.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/schema.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/tracker.ts
On the way to implement #1208
Add `old_data` field to the BQ changelog and view tables + tests
> feat(bg-change-tracker): add old_data field to the BQ record

- storage-resize-images/functions/src/index.ts
Re-introduced object data as input for resize-image `completion events`
> fix(storage-resize-images): re-add input object data to the complete event

- jest.config.js
> chore(firestore-bigquery-export): exclude local import script testing

- firestore-translate-text/extension.yaml
- firestore-translate-text/functions/__tests__/__snapshots__/config.test.ts.snap
- firestore-translate-text/functions/__tests__/config.test.ts
- firestore-translate-text/functions/__tests__/functions.test.ts
- firestore-translate-text/functions/src/config.ts
- firestore-translate-text/functions/src/index.ts
fixes: https://github.com/firebase/extensions/issues/1142
This PR allows for `LANGUAGE_FIELD_NAME` to be set. If a field with this name is added to a document to be translated, the extension will use the languages provided on this field.
> @invertase/languages field

- storage-resize-images/functions/__tests__/__snapshots__/config.test.ts.snap
- storage-resize-images/functions/src/config.ts
- storage-resize-images/functions/src/index.ts
fixes: #1389
Consider location (region) the extension is installed when loading task queue.
Previously regardless of which region the extension is installed, it will look for a the Task Queue in `us-central1`. 
See documentation for information: https://firebase.google.com/docs/reference/admin/node/firebase-admin.functions.functions.md#functionstaskqueue
> fix(storage-resize-images): support backfill task in custom region

- _emulator/extensions/firestore-send-email.env.local
- _emulator/extensions/firestore-send-email.secret.local
- firestore-send-email/extension.yaml
- firestore-send-email/functions/__tests__/config.test.ts
- firestore-send-email/functions/__tests__/e2e.test.ts
- firestore-send-email/functions/src/config.ts
- firestore-send-email/functions/src/index.ts
- firestore-send-email/functions/src/types.ts
This feature allows TTL support for firestore-send-email.
The dev can pick a value for the parameter `FIRESTORE_EXPIRE_AT` and the extension will automatically add an `expireAt` field to firestore records of emails, with a value relative to their creation. The dev can set up a TTL policy on their firestore database to delete these records.
fixes https://github.com/firebase/extensions/issues/1072
> feat(firestore-send-email): add TTL support

- storage-resize-images/functions/src/resize-image.ts
Switch storage-resize-images to always use POSIX paths when writing to Storage.
This addresses an issue (https://github.com/firebase/firebase-tools/issues/5430) where, when emulating this extension on a Windows machine, resized images would be written to the root of the bucket with the Windows path as the filename.
Fixes https://github.com/firebase/firebase-tools/issues/5430.
> [storage-resize-images] Always use posix paths when writing to storage

- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/bigquery/schema.test.ts
- firestore-counter/functions/package.json
- storage-resize-images/functions/__tests__/e2e.test.ts
Updates for the latest release caused issues when running tests from the root of the project.
> @invertase/fix release tests

- firestore-send-email/extension.yaml
This PR fixes a small typo in the extension.yaml
> fix(firestore-send-email): fix typo in extension

- firestore-bigquery-export/scripts/gen-schema-view/src/index.ts
- firestore-bigquery-export/scripts/import/src/index.ts
at the moment running this script will trigger a warning about certain environmental variables being undefined. This PR is to set them, as we do in the import script.
should fix https://github.com/firebase/extensions/issues/978
> fix(firestore-bigquery-export): set environmental variables after initialization

- firestore-bigquery-export/scripts/gen-schema-view/src/index.ts
This PR reverts a small patch, these lines were already present and did not need adding.
> chore(firestore-bigquery-export): revert PR to add envs (not needed)

- firestore-send-email/functions/src/index.ts
- firestore-send-email/functions/src/logs.ts
This PR moves the warning about missing messages until after the payload has been checked for template references. As mentioned [here ](https://github.com/firebase/extensions/issues/1418) this warning isn't necessary if a template is provided, as the message will be constructed from the template.
fixes: https://github.com/firebase/extensions/issues/1418
> fix(firestore-send-email): Move warning until after checking for templates

- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
Callable functions return the http response in the response.result field. To support setting the transform function to callable functions we can return the response.result.data field if it is defined, otherwise result the response.data field for http functions. Supporting callable transform functions can be useful for users that want to configure transform functions defined in other extensions, for example the Pangea Redact Text extension.
> fix(firestore-bigquery-export): Added support for callable transform functions 

- docs/firestore-translate-text/get-started.md
- firestore-translate-text/README.md
- firestore-translate-text/extension.yaml
- firestore-translate-text/functions/package.json
This PR renames the extension to "Translate Text in Firestore"
> chore(firestore-translate-text): rename extension

- firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md
As mentioned in the thread https://github.com/firebase/extensions/issues/1060 
Running the import script twice duplicates data, and it is not advised to be used as a resync, in its current behaviour.
> Update import script docs to warn about duplication on multiple runs

- firestore-counter/clients/node/index.js
- firestore-counter/clients/web/src/index.ts
(reopening https://github.com/firebase/extensions/pull/928 for testing purposes)
.substr() is deprecated so we replace it with .slice() which works similarily but isn't deprecated
> Replace deprecated String.prototype.substr()

- firestore-translate-text/functions/src/index.ts
- samples/rtdb-uppercase-messages/functions/index.js
It turns out that if you do not specify the location when getting a taskQueue, it defaults to us-central1 (https://github.com/firebase/firebase-admin-node/blob/master/src/functions/functions.ts#L50). This fixes an issue where these backfills would not work in other regions.
> Specify location for taskQueues so that they dont default to us-central1

- firestore-bigquery-export/scripts/import/src/index.ts
reopening https://github.com/firebase/extensions/pull/1542 because failing CI.
> fix(firestore-bigquery-export): improve help for --use-emulator

- delete-user-data/extension.yaml
- delete-user-data/functions/package-lock.json
- delete-user-data/functions/package.json
> chore(delete-user-data): bump to node 16

- firestore-bigquery-export/scripts/import/src/config.ts
For some reason these were removed in this refactor https://github.com/firebase/extensions/commit/0a246b1a8b8841120be308eae9806caa323ebdd8
this PR adds them back in. The package will probably need publishing
fixes https://github.com/firebase/extensions/issues/1692
> fix(firestore-bigquery-export): add missing locations back in

- storage-resize-images/functions/__tests__/__snapshots__/config.test.ts.snap
- storage-resize-images/functions/src/config.ts
This will suppress a warning which will happen if no default is provided in sharpOptions
> fix(storage-resize-images): default sharpOptions

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/firestore-bigquery-change-tracker/package-lock.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
- firestore-bigquery-export/functions/package.json
- firestore-bigquery-export/scripts/import/package.json
In version 0.1.37 of the extension, and the latest version of the import CLI script, a breaking change was introducedwhere timestamps were serialized to dates.
This should fix https://github.com/firebase/extensions/issues/1828 and https://github.com/firebase/extensions/issues/1813
This PR will need the changetracker releasing before CI will pass.
> fix(firestore-bigquery-export): rollback timestamp serialization

- firestore-send-email/extension.yaml
- firestore-send-email/functions/__tests__/helpers.test.ts
Potentially fixes #1472 by updating the validation regex for `SMTP_CONNECTION_URI`.
The new regex rule will check if a colon `:` is used instead of `@` before the SMTP server name.
These will be invalid:
```
smtps://username:smtp.hostname.com:465
smtps://username:password:smtp.hostname.com:465
```
This is valid:
```
smtps://username@smtp.hostname.com:465
smtps://username:password@smtp.hostname.com:465
```
> fix(firestore-send-email): update the regex to prevent unvalid URLs

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/functions/src/config.ts
This feature needs additional testing before it should be present in the extension.
> fix(firestore-bigquery-export): rollback backfill feature

- docs/firestore-bigquery-export/Clustering.md
- docs/firestore-bigquery-export/get-started.md
- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/functions/__tests__/__snapshots__/config.test.ts.snap
fixes [#1848](https://github.com/firebase/extensions/issues/1848)
> docs(firestore-bigquery-export): add document_name to clustering

- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/functions/src/index.ts
> fix(firestore-bigquery-export): make MAX_DISPATCHES_PER_SECOND take effect

- .github/workflows/test.yml
Node 14 will be deprecated soon in functions & all extensions' resources are now on node 16 and higher, hence is no need to run tests against it.
> ci: remove node14 from test matrix

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/extension.yaml
This applies configurations to the task queue which weren't taking effect.
> fix: add taskQueueTrigger configuration to extension.yaml

- docs/firestore-bigquery-export/cross-project-support.md
- firestore-bigquery-export/POSTINSTALL.md
Clarify additional IAM setup in docs and rename "alternative" project to cross-project support, specifying a separate GCP project ID for the BigQuery instance.
Should help with issues like #1861.
> docs(firestore-bigquery-export): clarify cross-project setup

- firestore-bigquery-export/scripts/import/src/config.ts
Parse parameter `batchSize` correctly in the interactive `import` script flow.
Fixes #1470 and #911
> fix(firestore-bigquery-export): parse batchSize correctly

- docs/firestore-send-email/get-started.md
- firestore-send-email/README.md
- firestore-send-email/extension.yaml
> docs(firestore-send-email): clarify FROM address not working with gmail

- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
This PR bumps the changetracker so we can release from `master`
> chore(firestore-bigquery-export): prep release (1 of 2)

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/functions/package-lock.json
- firestore-bigquery-export/functions/package.json
This PR is to bump the firestore-bigquery-export version ready for a release.
> chore(firestore-bigquery-export): prep release (2 of 2)

- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
> docs(firestore-bigquery-export): fix typo

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/firestore-bigquery-change-tracker/package-lock.json
- firestore-bigquery-export/functions/src/index.ts
- firestore-bigquery-export/scripts/gen-schema-view/package-lock.json
- firestore-bigquery-export/scripts/import/package-lock.json
The import documents feature on firestore-bigquery-export uses `offset` which is causing unnecessary (billed) reads.
This PR disables this feature until an alternative method is implemented.
Issue seen in #2000 and #2003
> fix(firestore-bigquery-export): disable backfill temporarily

- delete-user-data/test-data/package-lock.json
- delete-user-data/test-data/package.json
This bumps dependencies in the test-data utility of delete-user-data, just to silence dependabot
> chore(delete-user-data/test-data): run npm audit

- firestore-send-email/functions/__tests__/helpers.test.ts
- firestore-send-email/functions/src/helpers.ts
- firestore-send-email/functions/src/index.ts
- Use new SendGrid (v3) transport only when payload body contains `sendGrid` field
-  Fix an issue where `text` or `html` fields were `null` and not `undefined` which was resulting in an error.
Resolves #2004.
> fix(firestore-send-email): SendGrid v3 issues

- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
Replaces https://github.com/firebase/extensions/pull/2024 as CI was failing (we need to update that CI so it'll run from forks I think)
> docs(firestore-bigquery-export): clarify meaning of "exclude old data"

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/functions/__tests__/__snapshots__/config.test.ts.snap
- firestore-bigquery-export/functions/src/config.ts
- firestore-bigquery-export/functions/src/index.ts
- firestore-bigquery-export/functions/src/logs.ts
This PR adds logging of data on failure to enqueue in BQ extension
> fix(firestore-bigquery-export): log data and old data on fail to enqueue

- _emulator/.firebaserc
- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/tsconfig.json
- firestore-bigquery-export/functions/__tests__/__snapshots__/config.test.ts.snap
- firestore-bigquery-export/functions/__tests__/e2e.test.ts
- firestore-bigquery-export/functions/__tests__/functions.test.ts
- firestore-bigquery-export/functions/package-lock.json
- firestore-bigquery-export/functions/package.json
- firestore-bigquery-export/functions/src/config.ts
- firestore-bigquery-export/functions/src/index.ts
- firestore-bigquery-export/functions/src/logs.ts
- firestore-bigquery-export/functions/src/util.ts
- firestore-bigquery-export/functions/stress_test/count.js
- firestore-bigquery-export/functions/stress_test/main.js
- firestore-bigquery-export/functions/stress_test/worker.js
- firestore-bigquery-export/scripts/gen-schema-view/package-lock.json
- firestore-bigquery-export/scripts/import/package-lock.json
- firestore-bigquery-export/scripts/import/src/helper.ts
- firestore-bigquery-export/scripts/import/src/index.ts
- firestore-bigquery-export/scripts/import/src/worker.ts
This PR is to release firestore-bigquery-export extension
> release: firestore-export-bigquery

- firestore-bigquery-export/guides/OBSERVABILITY.md
This PR is to add a guide on observability in the new version of the firestore-bigquery-export extension.
> docs(firestore-bigquery-export): add observability guide

- firestore-translate-text/README.md
- firestore-translate-text/extension.yaml
This PR is to retrigger the release process, and fix a small grammar typo.
> docs(firestore-translate-text): fix extension.yaml description

- firestore-bigquery-export/POSTINSTALL.md
- firestore-bigquery-export/PREINSTALL.md
- firestore-bigquery-export/README.md
- firestore-bigquery-export/scripts/grant-crossproject-access.ps1
- firestore-bigquery-export/scripts/grant-crossproject-access.sh
Should resolve https://github.com/firebase/extensions/issues/2140
> docs(firestore-bigquery-export): provided scripts for cross-project streaming

- firestore-bigquery-export/functions/package-lock.json
- firestore-bigquery-export/scripts/gen-schema-view/package-lock.json
- firestore-send-email/functions/__tests__/helpers.test.ts
- firestore-send-email/functions/package-lock.json
- firestore-send-email/functions/package.json
- firestore-send-email/functions/src/helpers.ts
- firestore-send-email/functions/src/index.ts
- firestore-send-email/functions/src/logs.ts
- firestore-send-email/functions/src/types.ts
This PR addresses the following improvements and fixes for the Firestore-Send-Email extension:
Enhancement: Increase in Payload Fields
Developers can now include categories.
Introduced a dynamic method for detecting SendGrid usage based on the SMTP_CONNECTION_URI. 
Bug Fix: Categories Not Being Sent
The categories field was not properly passed to the SendGrid API in the previous implementation.
Modified the email preparation and transport logic to ensure that the categories field is passed as per SendGrid's requirements.
Refactored Code and Tests
Removed the unused nodemailer-sendgrid dependency to simplify the codebase and avoid confusion.
Updated helpers.ts and corresponding tests in helpers.test.ts to support the new dynamic SendGrid detection.
Added logs to indicate whether the email …
> fix: add support for SendGrid categories and streamline SendGrid detection

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/functions/__tests__/__snapshots__/config.test.ts.snap
wait for https://github.com/firebase/extensions/pull/2255
part of fix for https://github.com/firebase/extensions/issues/2134
> fix(firestore-bigquery-export): do not cluster invalid types

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/functions/__tests__/functions.test.ts
- firestore-bigquery-export/functions/src/events.ts
https://github.com/firebase/extensions/issues/1981
Description (issue 1981):
This PR introduces backward-compatible event types while adding new naming conventions for Firestore BigQuery Export. The changes ensure robust event handling across multiple versions of the extension. The following updates have been made:
Key Changes:
1.	New Event Types:
•	Introduced new events using the updated naming convention:
•	firebase.extensions.firestore-bigquery-export.v1.onStart
•	firebase.extensions.firestore-bigquery-export.v1.onSuccess
•	firebase.extensions.firestore-bigquery-export.v1.onError
•	firebase.extensions.firestore-bigquery-export.v1.onCompletion
2.	Backward Compatibility:
•	Maintains the existing events under the old naming convention:
•	firebase.extensions.firestore-counter.v1.*
•	Both …
> fix(firestore-bigquery-export): Add Backward Compatibility and New Event Types for Firestore BigQuery Export

- firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md
- firestore-bigquery-export/scripts/import/__tests__/getRowsFromDocs.test.ts
- firestore-bigquery-export/scripts/import/__tests__/runMultiThread.test.ts
- firestore-bigquery-export/scripts/import/__tests__/runMultiThreadMock.test.ts
- firestore-bigquery-export/scripts/import/package-lock.json
- firestore-bigquery-export/scripts/import/package.json
- firestore-bigquery-export/scripts/import/src/config.ts
- firestore-bigquery-export/scripts/import/src/helper.ts
- firestore-bigquery-export/scripts/import/src/index.ts
- firestore-bigquery-export/scripts/import/src/program.ts
- firestore-bigquery-export/scripts/import/src/run-multi-thread.ts
- firestore-bigquery-export/scripts/import/src/run-single-thread.ts
- firestore-bigquery-export/scripts/import/src/types.ts
- firestore-bigquery-export/scripts/import/src/worker.ts
provides fixes for:
fixes https://github.com/firebase/extensions/issues/2132
fixes https://github.com/firebase/extensions/issues/2055
fixes https://github.com/firebase/extensions/issues/1852
This PR:
- fixes path_params in multi-threaded, they no longer import as `null` in BQ
- sets the bigquery project ID in the changetracker instance (instead of an environment variable, which was pointing the firebase client at the wrong project)
- ensures that the multi-thread feature does not exceed the batch size option when writing to bigquery (mostly done in worker.ts)
- on a failed batch, instead of the whole script failing, the script will now just log the paths of the failed docs, and there is an option to output a `.txt` file with newline separated document paths of failed imports
> feat(firestore-bigquery-export): import script updates

- storage-resize-images/functions/src/resize-image.ts
The extension documentation says
> This extension keeps the aspect ratio of uploaded images constant and shrinks the image until the resized image’s dimensions are at or under your specified max width and height.
However, it doesn't currently do that: this pull request fixes it.
Fixes #2106
> fix(storage-resize-images): maintain aspect ratio of resized images

- delete-user-data/CHANGELOG.md
- delete-user-data/extension.yaml
- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/extension.yaml
- firestore-counter/CHANGELOG.md
- firestore-counter/extension.yaml
- firestore-send-email/CHANGELOG.md
- firestore-send-email/extension.yaml
- firestore-shorten-urls-bitly/CHANGELOG.md
- firestore-shorten-urls-bitly/extension.yaml
- firestore-translate-text/CHANGELOG.md
- firestore-translate-text/extension.yaml
- rtdb-limit-child-nodes/CHANGELOG.md
- rtdb-limit-child-nodes/extension.yaml
- storage-resize-images/CHANGELOG.md
- storage-resize-images/extension.yaml
This PR should resolve the following:
fixes: https://github.com/firebase/extensions/issues/2277
fixes: https://github.com/firebase/extensions/issues/2252
> chore(*): bump all functions to nodejs20 runtime

- .github/workflows/readmes-updated.yml
[Soon to be deprecated](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down)
> fix(workflows): update from actions/cache v2 to v4

- firestore-send-email/CHANGELOG.md
- firestore-send-email/functions/src/index.ts
> fix(firestore-send-email): 'replyTo' no longer required

- firestore-send-email/extension.yaml
This new param should be optional i think.
> fix(firestore-send-email): make oauth user optional

- firestore-send-email/CHANGELOG.md
- firestore-send-email/functions/src/index.ts
fixes https://github.com/firebase/extensions/issues/2306
> fix(firestore-send-email): support attachments in sendgrid

- firestore-translate-text/README.md
- firestore-translate-text/extension.yaml
- firestore-translate-text/functions/src/config.ts
This PR removes leftover resources in the extension for the removed backfill feature.
> chore(firestore-translate-text): fully remove backfill resources

- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/changeTracker.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/logger.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/index.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/logger.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/logs.ts
This PR is to release a new version of the change tracker package
> Release @firebaseextensions/firestore-bigquery-change-tracker 

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/functions/__tests__/__snapshots__/config.test.ts.snap
- firestore-bigquery-export/functions/__tests__/functions.test.ts
- firestore-bigquery-export/functions/package-lock.json
- firestore-bigquery-export/functions/package.json
- firestore-bigquery-export/functions/src/config.ts
- firestore-bigquery-export/functions/src/index.ts
- firestore-bigquery-export/functions/src/logs.ts
This PR is to release a new version of firestore-bigquery-export
> Release 17/03/25

- firestore-shorten-urls-bitly/extension.yaml
This needs to be required (a default is provided)
> fix(firestore-shorten-urls-bitly): make database param required

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/functions/src/index.ts
This PR fixes a potential bug with the backup enqueue feature of this extension, and improves type safety.
> fix(firestore-bigquery-export): fix types passed to syncBigQuery queue

- firestore-send-email/CHANGELOG.md
- firestore-send-email/extension.yaml
- firestore-send-email/functions/src/index.ts
Resolves https://github.com/firebase/extensions/issues/2372
Tested
> fix(firestore-send-email): fix issue with empty message property causing error when using SendGrid

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/extension.yaml
- firestore-shorten-urls-bitly/CHANGELOG.md
- firestore-shorten-urls-bitly/extension.yaml
This PR removes the incorrect default: us value for database region on firestore v2 triggers
> feat(*): remove default database region on v2 triggers

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/functions/__tests__/__snapshots__/config.test.ts.snap
- firestore-bigquery-export/functions/src/config.ts
- firestore-bigquery-export/functions/src/index.ts
This PR is to release firestore-bigquery-export extension
> Release firestore-bigquery-export

- firestore-send-email/CHANGELOG.md
- firestore-send-email/POSTINSTALL.md
- firestore-send-email/extension.yaml
- firestore-send-email/functions/__tests__/nodemailer-sendgrid/index.test.ts
- firestore-send-email/functions/jest.config.js
- firestore-send-email/functions/src/index.ts
- firestore-send-email/functions/src/nodemailer-sendgrid/index.ts
- firestore-send-email/functions/src/nodemailer-sendgrid/types.ts
- firestore-send-email/functions/src/types.ts
Resolves https://github.com/firebase/extensions/issues/2375
This PR includes the sendgrid queue ID as well as the message ID when writing back to firestore
We have refactored to wrap the HTTP SDK for sendgrid in a custom transport
TODO:
> fix(firestore-send-email): add types and attempt to extract message ID

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/extension.yaml
- Updated BigQuery Dataset Locations. 
- Removed duplicate locations.
Fixes https://github.com/firebase/extensions/issues/2305
> feat(firestore-bigquery-export): Add bigquery dataset locations

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/firestore-bigquery-change-tracker/package-lock.json
- firestore-bigquery-export/scripts/import/src/index.ts
- firestore-bigquery-export/scripts/import/src/run-single-thread.ts
- firestore-send-email/CHANGELOG.md
- firestore-send-email/POSTINSTALL.md
- firestore-send-email/extension.yaml
- firestore-send-email/functions/__tests__/nodemailer-sendgrid/index.test.ts
- firestore-send-email/functions/__tests__/validation.test.ts
- firestore-send-email/functions/jest.config.js
- firestore-send-email/functions/package-lock.json
- firestore-send-email/functions/package.json
- firestore-send-email/functions/src/index.ts
- firestore-send-email/functions/src/nodemailer-sendgrid/index.ts
- firestore-send-email/functions/src/nodemailer-sendgrid/types.ts
- firestore-send-email/functions/src/types.ts
- firestore-send-email/functions/src/validation.ts
This PR will trigger the release for firestore-send-email
> Release firestore-send-email and firestore-bigquery-export extensions 

- firestore-send-email/CHANGELOG.md
- firestore-send-email/POSTINSTALL.md
- firestore-send-email/PREINSTALL.md
- firestore-send-email/README.md
- firestore-send-email/extension.yaml
This PR adds docs for using dynamic templates with SendGrid in firestore-send-email.
fixes https://github.com/firebase/extensions/issues/2363
> docs(firestore-send-email): add docs on dynamic SendGrid templates

- firestore-send-email/CHANGELOG.md
- firestore-send-email/functions/__tests__/e2e/sendgrid.test.ts
- firestore-send-email/functions/__tests__/prepare-payload.test.ts
- firestore-send-email/functions/__tests__/validation.test.ts
- firestore-send-email/functions/jest.config.js
- firestore-send-email/functions/package.json
- firestore-send-email/functions/src/index.ts
- firestore-send-email/functions/src/prepare-payload.ts
- firestore-send-email/functions/src/validation.ts
This PR is to actually fix https://github.com/firebase/extensions/issues/2419
We extract preparePayload into a dependency injection pattern, and cover it with unit tests, and ensure template/message merging is being done correctly
> fix(firestore-send-email): preparePayload fix

- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/partitioning.ts
Resolves https://github.com/firebase/extensions/issues/2303
> fix(firestore-bigquery-change-tracker): keep partition value on delete using old data

- firestore-bigquery-export/firestore-bigquery-change-tracker/package-lock.json
- firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md
- firestore-bigquery-export/scripts/gen-schema-view/package-lock.json
- firestore-bigquery-export/scripts/gen-schema-view/package.json
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/genkit/sampleFirestoreDocuments.test.ts
- firestore-bigquery-export/scripts/gen-schema-view/src/schema/genkit.ts
- firestore-counter/clients/web/package-lock.json
- firestore-translate-text/CHANGELOG.md
- firestore-translate-text/PREINSTALL.md
- firestore-translate-text/README.md
- firestore-translate-text/extension.yaml
- firestore-translate-text/functions/package-lock.json
- firestore-translate-text/functions/package.json
- firestore-translate-text/functions/src/config.ts
- firestore-translate-text/functions/src/translate/common.ts
- storage-resize-images/CHANGELOG.md
- storage-resize-images/PREINSTALL.md
- storage-resize-images/README.md
- storage-resize-images/extension.yaml
- storage-resize-images/functions/__tests__/__snapshots__/config.test.ts.snap
- storage-resize-images/functions/__tests__/filters.test.ts
- storage-resize-images/functions/__tests__/function.test.ts
- storage-resize-images/functions/package-lock.json
- storage-resize-images/functions/src/config.ts
- storage-resize-images/functions/src/index.ts
This PR releases:
- gen-schema-view
- firestore-translate-text
- storage-resize-images
> Release: 22nd July 2025
