- storage-resize-images/CHANGELOG.md
- storage-resize-images/extension.yaml
Format of changelog will probably change in the future (since we may be automating the generation of it). But this is just something to have for now.
> [storage-resize-images] Update to v0.1.1

- firestore-bigquery-export/scripts/gen-schema-view/package.json
- firestore-bigquery-export/scripts/gen-schema-view/src/index.ts
- firestore-bigquery-export/scripts/gen-schema-view/src/logs.ts
- firestore-bigquery-export/scripts/gen-schema-view/src/schema.ts
- firestore-bigquery-export/scripts/gen-schema-view/src/snapshot.ts
- firestore-bigquery-export/scripts/gen-schema-view/src/udf.ts
These are strictly formatting changes.
> [fs-bq-export] add prettier formatting for fs-bq-schema-views script

- delete-user-data/CHANGELOG.md
> chore(delete-user-data): Update changelog version

- firestore-send-email/POSTINSTALL.md
- firestore-send-email/functions/lib/index.js
- firestore-send-email/functions/lib/logs.js
- firestore-send-email/functions/lib/templates.js
- firestore-send-email/functions/src/index.ts
Fixes:
- https://github.com/firebase/extensions/issues/77
- https://github.com/firebase/extensions/issues/76 (part fix)
This PR allows users to attach additional headers to the mail.
> feat(firestore-send-email) Attach headers to nodemailer

- .github/ISSUE_TEMPLATE/bug.md
Prompting the developer for the extension version that they're currently using might be helpful for us to be able to reproduce the bug they're experiencing.
This PR should add that field to our Bug Report issue template.
> chore(*): update bug report issue template

- .github/CODEOWNERS
Updated as per https://github.com/firebase/extensions/pull/98#issuecomment-551266401
cc @rachelsaunders
> chore(*): update CODEOWNERS

- firestore-bigquery-export/POSTINSTALL.md
- firestore-bigquery-export/PREINSTALL.md
- firestore-bigquery-export/guides/EXAMPLE_QUERIES.md
- firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md
- add instructions file for setting up for and running the schema-views script
- add example queries file for use with the schema-views script
- add references to PRE/POSTINSTALL file for schema-views script
- tighten up existing import script section to align with new schema-views script section in PRE/POSTINSTALL files
Issue #139
> docs(firestore-bigquery-export) Add instructions, information, and references for schema-views script

- firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md
> docs(firestore-bigquery-export) Add Firestore `reference` type to supported types in schema-views script instructions 

- firestore-send-email/PREINSTALL.md
> docs(firestore-send-email): add note about bulk email service providers

- firestore-counter/functions/lib/aggregator.js
- firestore-counter/functions/lib/controller.js
- firestore-counter/functions/lib/worker.js
- firestore-counter/functions/src/aggregator.ts
- firestore-counter/functions/src/controller.ts
- firestore-counter/functions/src/worker.ts
- firestore-counter/functions/test/aggregator.ts
- firestore-counter/package.json
- package-lock.json
> chore(firestore-counter): update firebase-admin & firebase-functions packages

- auth-mailchimp-sync/extension.yaml
- delete-user-data/extension.yaml
- firestore-bigquery-export/extension.yaml
- firestore-counter/extension.yaml
- firestore-send-email/extension.yaml
- firestore-shorten-urls-bitly/extension.yaml
- firestore-translate-text/extension.yaml
- rtdb-limit-child-nodes/extension.yaml
- storage-resize-images/extension.yaml
Each extension.yaml file had a slightly different ordering and spacing for its fields.  This PR aligns this ordering and spacing across all extensions.
> chore(*): aligned the order and spacing of fields within extension.yaml files

- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
- firestore-bigquery-export/scripts/import/package.json
- firestore-bigquery-export/scripts/import/src/index.ts
related to [#192](https://github.com/firebase/extensions/issues/192)
> fix(fs-bq-import-collection): update bigquery lib and insert api usage

- firestore-counter/functions/lib/index.js
- firestore-counter/functions/src/index.ts
> refactor(firestore-counter): use handlers

- auth-mailchimp-sync/POSTINSTALL.md
- delete-user-data/POSTINSTALL.md
- firestore-bigquery-export/POSTINSTALL.md
- firestore-counter/POSTINSTALL.md
- firestore-send-email/POSTINSTALL.md
- firestore-shorten-urls-bitly/POSTINSTALL.md
- firestore-translate-text/POSTINSTALL.md
- rtdb-limit-child-nodes/POSTINSTALL.md
- storage-resize-images/POSTINSTALL.md
- make sure parameter syntax references use `${param:PARAMETER_NAME}`
- fix formatting, as needed, like obnoxious hyperlinks or unnecessary backticks
- wordsmith/clarify some intro sentences (especially in regards to the "Firebase console" and fragments)
> docs(*): performed copy-edits to POSTINSTALL files

- auth-mailchimp-sync/extension.yaml
- delete-user-data/extension.yaml
- firestore-bigquery-export/extension.yaml
- firestore-counter/extension.yaml
- firestore-send-email/extension.yaml
- firestore-shorten-urls-bitly/extension.yaml
- firestore-translate-text/extension.yaml
- rtdb-limit-child-nodes/extension.yaml
- storage-resize-images/extension.yaml
Quick test to check region is working;
> chore(*): add europe-west3 location

- .github/workflows/scripts/release.sh
Fixes the release automation script (`Not Found` error).
Additionally tweaked the logging format and changed the update functionality to only update and existing release if the release body contents are not identical to the contents of the release extracted from `CHANGELOG.md`
- **Updating an existing release where changelog has been updated**:
- **Creating a new release if one wasn't found (Not Found error would have prevented this previously):**
> fix: release automation script

- .github/workflows/scripts/release.sh
- Added 'v' to version tag and release name to match existing releases
- Added a temporary manual excludes list to ignore current latest published version of each extension that are already on master as of last release. This works around the last release missing 'v' from their names/tags & some of the other manually done releases that don't match the correct naming format.
- This can be eventually removed once a new version of each Extension has been published via the release script.
- Removed unnecessary master branch check - CI trigger is already set to master only
**Skips all extensions & versions defined in `SKIP_EXTENSION_VERSIONS`:**
**Successfully creates an Extension release when it no longer matches any of the excluded versions defined in `SKIP_EXTENSION_VERSIONS`** (locally …
> fix: release automation script duplication

- firestore-bigquery-export/scripts/gen-schema-view/src/udf.ts
issue: https://github.com/firebase/extensions/issues/318
> fix(firestore-bigquery-export): Fix input args for ST_GEOGPOINT construction

- firestore-translate-text/PREINSTALL.md
- firestore-translate-text/README.md
- firestore-translate-text/functions/__tests__/functions.test.ts
> docs(firestore-translate-text): update

- firestore-counter/POSTINSTALL.md
You might have already been doing this, but if not, here's a pass at it.
> Add upgrade info to counter extension

- firestore-send-email/POSTINSTALL.md
Do not merge until console changes.
> send-email: Fix console deeplinks to Firestore for upcoming Cloud Firestore/Realtime Database split

- firestore-bigquery-export/PREINSTALL.md
- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/logs.ts
- firestore-bigquery-export/functions/lib/index.js
- firestore-bigquery-export/functions/lib/logs.js
- firestore-bigquery-export/functions/lib/util.js
- firestore-bigquery-export/package.json
- firestore-bigquery-export/tsconfig.json
> chore(firestore-bigquery-export): migration to Node.js v10

- firestore-shorten-urls-bitly/PREINSTALL.md
- firestore-shorten-urls-bitly/extension.yaml
- firestore-shorten-urls-bitly/functions/README.md
- firestore-shorten-urls-bitly/functions/lib/abstract-shortener.js
- firestore-shorten-urls-bitly/functions/lib/index.js
- firestore-shorten-urls-bitly/functions/lib/logs.js
- firestore-shorten-urls-bitly/functions/package.json
- firestore-shorten-urls-bitly/functions/src/logs.ts
- firestore-shorten-urls-bitly/functions/tsconfig.json
> chore(firestore-shorten-urls-bitly): migration to Node.js v10

- storage-resize-images/PREINSTALL.md
- storage-resize-images/README.md
- storage-resize-images/extension.yaml
- storage-resize-images/functions/lib/index.js
- storage-resize-images/functions/lib/logs.js
- storage-resize-images/functions/src/logs.ts
- storage-resize-images/package.json
- storage-resize-images/tsconfig.json
> chore(storage-resize-images): migration to Node.js v10

- rtdb-limit-child-nodes/PREINSTALL.md
- rtdb-limit-child-nodes/extension.yaml
- rtdb-limit-child-nodes/functions/README.md
- rtdb-limit-child-nodes/functions/lib/index.js
- rtdb-limit-child-nodes/functions/lib/logs.js
- rtdb-limit-child-nodes/functions/package.json
- rtdb-limit-child-nodes/functions/src/logs.ts
- rtdb-limit-child-nodes/functions/tsconfig.json
> chore(rtdb-limit-child-nodes): migration to Node.js v10

- auth-mailchimp-sync/CHANGELOG.md
- auth-mailchimp-sync/extension.yaml
- delete-user-data/CHANGELOG.md
- delete-user-data/extension.yaml
- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/extension.yaml
- firestore-counter/CHANGELOG.md
- firestore-counter/extension.yaml
- firestore-send-email/CHANGELOG.md
- firestore-send-email/extension.yaml
- firestore-shorten-urls-bitly/CHANGELOG.md
- firestore-shorten-urls-bitly/extension.yaml
- firestore-translate-text/CHANGELOG.md
- firestore-translate-text/extension.yaml
- rtdb-limit-child-nodes/CHANGELOG.md
- rtdb-limit-child-nodes/extension.yaml
- storage-resize-images/CHANGELOG.md
- storage-resize-images/extension.yaml
https://github.com/firebase/extensions/pull/448
> Update changelogs for September 10, 2020 release

- auth-mailchimp-sync/extension.yaml
- delete-user-data/extension.yaml
- firestore-bigquery-export/extension.yaml
- firestore-counter/extension.yaml
- firestore-send-email/extension.yaml
- firestore-shorten-urls-bitly/extension.yaml
- firestore-shorten-urls-dynamic-links/extension.yaml
- firestore-translate-text/extension.yaml
- rtdb-limit-child-nodes/extension.yaml
- storage-resize-images/extension.yaml
Update `${PARAMETER_NAME}` to `${param:PARAMETER_NAME}`
fixes #331
> chore(*): update extension.yaml param syntax

- delete-user-data/CHANGELOG.md
- delete-user-data/extension.yaml
- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/extension.yaml
- firestore-send-email/CHANGELOG.md
- firestore-send-email/extension.yaml
- storage-resize-images/CHANGELOG.md
- storage-resize-images/extension.yaml
To go along with the updates in #564
> Jan 14, 2021 release notes

- firestore-bigquery-export/scripts/gen-schema-view/schemas/user_array.json
- firestore-bigquery-export/scripts/gen-schema-view/src/udf.ts
- firestore-bigquery-export/scripts/import/src/index.ts
fixes: https://github.com/firebase/extensions/issues/611
> fix(firestore-bigquery-export): remove double quotes on string arrays

- firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md
fixes: https://github.com/firebase/extensions/issues/596
> docs(firestore-bigquert-export): Updated documentation for gen-schema column overides

- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
fixes https://github.com/firebase/extensions/issues/621
> chore(firestore-bigquery-change-tracker): increment version to 1.1.12

- firestore-bigquery-export/scripts/gen-schema-view/package.json
- firestore-bigquery-export/scripts/import/package.json
Following PR merge, I'll trigger the workflow to publish the new versions of the scripts NPM package.
> Bump version of gen-schema-view and import scripts.

- delete-user-data/extension.yaml
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-counter/extension.yaml
- firestore-send-email/extension.yaml
- firestore-shorten-urls-bitly/extension.yaml
- firestore-translate-text/extension.yaml
- rtdb-limit-child-nodes/extension.yaml
- storage-resize-images/extension.yaml
fixes https://github.com/firebase/extensions/pull/663
> feat(*): added warsaw (europe-central2) location

- storage-resize-images/PREINSTALL.md
- storage-resize-images/README.md
- storage-resize-images/extension.yaml
- storage-resize-images/functions/__tests__/tsconfig.json
- storage-resize-images/functions/package.json
- storage-resize-images/functions/tsconfig.json
> chore(storage-resize-images): migration to Node.js v14

- delete-user-data/PREINSTALL.md
- delete-user-data/README.md
- delete-user-data/extension.yaml
- delete-user-data/functions/package.json
- delete-user-data/functions/tsconfig.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
> chore(delete-user-data): migration to Node.js v14

- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-counter/PREINSTALL.md
- firestore-counter/README.md
- firestore-counter/extension.yaml
- firestore-counter/functions/package.json
- firestore-counter/functions/tsconfig.json
> chore(firestore-counter): migration to Node.js v14

- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-send-email/PREINSTALL.md
- firestore-send-email/README.md
- firestore-send-email/extension.yaml
- firestore-send-email/functions/package.json
- firestore-send-email/functions/tsconfig.json
> chore(firestore-send-email): migration to Node.js v14

- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- rtdb-limit-child-nodes/PREINSTALL.md
- rtdb-limit-child-nodes/README.md
- rtdb-limit-child-nodes/extension.yaml
- rtdb-limit-child-nodes/functions/package.json
- rtdb-limit-child-nodes/functions/tsconfig.json
> chore(rtdb-limit-child-nodes): migration to Node.js v14

- firestore-bigquery-export/PREINSTALL.md
- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/tsconfig.json
- firestore-bigquery-export/functions/package.json
- firestore-bigquery-export/functions/tsconfig.json
Reverts firebase/extensions#662. Rollback to address #681
> Revert "chore(firestore-bigquery-export): migration to Node.js v14"

- firestore-send-email/functions/lib/logs.js
- firestore-send-email/functions/lib/templates.js
- firestore-send-email/functions/src/logs.ts
- firestore-send-email/functions/src/templates.ts
fixes: https://github.com/firebase/extensions/issues/209
> fix(firestore-send-email): added fallback for finding email templates

- delete-user-data/extension.yaml
fixes: https://github.com/firebase/extensions/issues/676
> chore(delete-user-data): update rtdb to be optional

- auth-mailchimp-sync/extension.yaml
- delete-user-data/extension.yaml
- firestore-bigquery-export/extension.yaml
- firestore-counter/extension.yaml
- firestore-send-email/extension.yaml
- firestore-shorten-urls-bitly/extension.yaml
- firestore-translate-text/extension.yaml
- rtdb-limit-child-nodes/extension.yaml
- storage-resize-images/extension.yaml
Separating PR https://github.com/firebase/extensions/pull/720
> feat(*): add Taiwan and Singapore Cloud Function Locations

- firestore-bigquery-export/guides/EXAMPLE_QUERIES.md
Updated document query for  https://github.com/firebase/extensions/issues/652
> chore(firestore-bigquery-export) updated example query to include deleted records

- delete-user-data/functions/package.json
- delete-user-data/test-data/package.json
Separating PR https://github.com/firebase/extensions/pull/720
> chore(delete-user-data): updated dependencies

- delete-user-data/functions/lib/index.js
- delete-user-data/functions/lib/logs.js
- delete-user-data/functions/package-lock.json
- delete-user-data/functions/tsconfig.json
Co-authored-by: Darren Ackers <ackers86@hotmail.com>
Co-authored-by: Daniel Smolinski <posiek07@gmail.com>
> fix(delete-user-data): updated typescript compiler

- firestore-bigquery-export/PREINSTALL.md
- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/snapshot.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
- firestore-bigquery-export/functions/__tests__/__snapshots__/config.test.ts.snap
- firestore-bigquery-export/functions/__tests__/config.test.ts
- firestore-bigquery-export/functions/lib/config.js
- firestore-bigquery-export/functions/lib/index.js
- firestore-bigquery-export/functions/src/config.ts
- firestore-bigquery-export/functions/src/index.ts
Reverts firebase/extensions#756
> Revert "feat(firestore-bigquery-export): add support for transforming data via a callable function"

- firestore-bigquery-export/scripts/gen-schema-view/src/schema.ts
fixes: https://github.com/firebase/extensions/issues/627
> fix: added fields null check when generating schemas

- delete-user-data/README.md
- delete-user-data/extension.yaml
- delete-user-data/functions/__tests__/helpers.test.ts
- delete-user-data/functions/lib/config.js
- delete-user-data/functions/lib/helpers.js
- delete-user-data/functions/lib/index.js
- delete-user-data/functions/package-lock.json
- delete-user-data/functions/package.json
- delete-user-data/functions/src/config.ts
- delete-user-data/functions/src/helpers.ts
- delete-user-data/functions/src/index.ts
fixes: #795
- add Realtime Database location choice to extensions.yaml
- refactor SELECTED_DATABASE_INSTANCE to camelcase letters (selectedDatabaseInstance)
- add selectedDatabaseLocation
- add getDatabaseUrl function with tests
- fix condition by checking if databaseUrl exist (was provided by user)
- update README.md
**Update Engine**
**Installed Extension**
**Extension Settings**
Belgium(west-europe1) RTDB
United States(us-central1) RTDB
**Added data**
Belgium(west-europe1) RTDB
United States(us-central1) RTDB
**Extension succesful logs**
Belgium(west-europe1) RTDB
United States(us-central1) RTDB
> fix(delete-user-data): add RTDB locations function

- storage-resize-images/README.md
- storage-resize-images/extension.yaml
fix: #745
**Description**
Improved documentation and installation instructions for IMAGE_TYPE conversion parameter.
> fix(storage-resize-images): update file types description

- auth-mailchimp-sync/CHANGELOG.md
- auth-mailchimp-sync/extension.yaml
- delete-user-data/CHANGELOG.md
- delete-user-data/extension.yaml
- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/extension.yaml
- firestore-counter/CHANGELOG.md
- firestore-counter/extension.yaml
- firestore-send-email/CHANGELOG.md
- firestore-send-email/extension.yaml
- firestore-shorten-urls-bitly/CHANGELOG.md
- firestore-shorten-urls-bitly/extension.yaml
- firestore-translate-text/CHANGELOG.md
- firestore-translate-text/extension.yaml
- rtdb-limit-child-nodes/CHANGELOG.md
- rtdb-limit-child-nodes/extension.yaml
- storage-resize-images/CHANGELOG.md
- storage-resize-images/extension.yaml
```
firestore-bigquery-export
firestore-send-email
storage-resize-images
delete-user-data
firestore-counter
auth-mailchimp-sync
firestore-shorten-urls-bitly
firestore-translate-text
rtdb-limit-child-nodes
```
> Bumped versions and update changelogs

- README.md
Adding message to recruit for upcoming user study on the Extensions emulator. I'll follow up with another PR to revert this on March 23.
> Adding message for upcoming user study

- firestore-send-email/extension.yaml
- firestore-send-email/functions/__tests__/helpers.test.ts
Update SMTP connection URI parameter validation Regex to accept query params. 
fixes: #940
> Update SMTP connection URI validation regex

- firestore-bigquery-export/scripts/gen-schema-view/package-lock.json
- firestore-bigquery-export/scripts/gen-schema-view/package.json
- firestore-bigquery-export/scripts/import/package-lock.json
- firestore-bigquery-export/scripts/import/package.json
> chore(firestore-bigquery-export): updated change tracker for bq scripts

- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/firestore-bigquery-change-tracker/package-lock.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/stresstest.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/logs.ts
- firestore-bigquery-export/functions/__tests__/__snapshots__/config.test.ts.snap
- firestore-bigquery-export/functions/package-lock.json
- firestore-bigquery-export/functions/package.json
- firestore-bigquery-export/scripts/import/src/config.ts
- firestore-bigquery-export/scripts/import/src/index.ts
- firestore-bigquery-export/scripts/import/src/run.ts
- firestore-send-email/functions/__tests__/e2e.test.ts
- firestore-send-email/functions/__tests__/helpers.test.ts
- firestore-send-email/functions/src/helpers.ts
- firestore-send-email/functions/src/logs.ts
- firestore-send-email/functions/src/templates.ts
PR to fix conflicts between `master` and `next`. As both are protected branches, the base must be master to resolve the expected conflicts from a new PR.
*Do Not Merge*
> chore(*): additional conflict resolutions

- firestore-bigquery-export/scripts/gen-schema-view/package-lock.json
- firestore-bigquery-export/scripts/gen-schema-view/package.json
- firestore-bigquery-export/scripts/import/package-lock.json
- firestore-bigquery-export/scripts/import/package.json
> chore(firestore-bigquery-export): bump script versions

- storage-resize-images/PREINSTALL.md
> docs(firestore-resize-images):add docs about required permissions to write custom event handlers

- delete-user-data/functions/src/helpers.ts
> chore(delete-user-data): added license headers for helper functions

- firestore-bigquery-export/extension.yaml
This PR addresses the issue https://github.com/firebase/extensions/issues/1025
> feat(firestore-bigquery-export): update confusing param prompts

- storage-resize-images/extension.yaml
> docs(storage-resize-images): deletion of original file description

- firestore-send-email/PREINSTALL.md
- firestore-send-email/README.md
> docs(firestore-send-email): add google app passwords guide

- storage-resize-images/extension.yaml
> feat(storage-resize-images): update IMG_BUCKET param type to selectResource

- storage-resize-images/PREINSTALL.md
- storage-resize-images/README.md
- storage-resize-images/extension.yaml
- storage-resize-images/functions/src/resize-image.ts
fixes: https://github.com/firebase/extensions/issues/1209 (reopening https://github.com/firebase/extensions/pull/1220)
> feat(storage-resize-images): add AVIF codec support

- docs/firestore-bundle-builder/get-started.md
> docs: updated firestore bundle builder links

- firestore-bigquery-export/functions/src/index.ts
> feat(firestore-bigquery-export): add oldData to the record

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/functions/package-lock.json
- firestore-bigquery-export/functions/package.json
> chore(firestore-bigquery-export): updated the change tracker version

- firestore-send-email/POSTINSTALL.md
- firestore-send-email/PREINSTALL.md
- storage-resize-images/POSTINSTALL.md
- storage-resize-images/PREINSTALL.md
Added a new section "**Further reading & resources**" to the following extensions:
- [storage-resize-images](https://github.com/firebase/extensions/tree/next/storage-resize-images)
- [firestore-send-email](https://github.com/firebase/extensions/tree/next/firestore-send-email)
Section added to both `POSTINSTALL` and `PREINSTALL`.
> docs: add further resources

- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/handleFailedTransactions.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/logs.ts
- firestore-bigquery-export/scripts/import/src/index.ts
fixes: https://github.com/firebase/extensions/pull/1310
> fix: add optional chaining to forEach method calls, to prevent undefined errors

- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/partitioning.ts
fixes: https://github.com/firebase/extensions/issues/1039
fixes: https://github.com/firebase/extensions/issues/1059
https://github.com/firebase/extensions/issues/621
> fix(firestore-bigquery-export): fixed partition data sync

- storage-resize-images/README.md
- storage-resize-images/extension.yaml
fixes: https://github.com/firebase/extensions/issues/1245
> Update storage-resize-images docs

- firestore-bigquery-export/scripts/gen-schema-view/src/index.ts
- firestore-bigquery-export/scripts/import/src/index.ts
fixes https://github.com/firebase/extensions/issues/1454 and https://github.com/firebase/extensions/issues/1442
> fix(firestore-bigquery-export): add checks for existing firebase apps

- firestore-send-email/functions/__tests__/e2e.test.ts
- firestore-send-email/functions/src/index.ts
fixes: https://github.com/firebase/extensions/issues/1418
> fix(firestore-send-email): added template check when no message exists

- docs/firestore-shorten-urls-bitly/get-started.md
- firestore-shorten-urls-bitly/README.md
- firestore-shorten-urls-bitly/extension.yaml
This PR renames the extension to "Shorten URLs in Firestore"
> chore(firestore-shorten-urls-bitly): rename extension

- delete-user-data/README.md
- delete-user-data/extension.yaml
- package.json
updates docs (see https://github.com/firebase/extensions/issues/1505 )
> docs(delete-user-data): make docs more clear on custom function

- firestore-counter/CHANGELOG.md
- firestore-counter/extension.yaml
Failed RC testing. Reverting update.
> chore(firestore-counter): revert release update

- storage-resize-images/README.md
- storage-resize-images/extension.yaml
fixes https://github.com/firebase/extensions/issues/1554
> fix(storage-resize-images): correct include path list description

- firestore-bigquery-export/PREINSTALL.md
- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/firestore-bigquery-change-tracker/package-lock.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
- firestore-bigquery-export/functions/__tests__/__snapshots__/config.test.ts.snap
- firestore-bigquery-export/functions/__tests__/config.test.ts
- firestore-bigquery-export/functions/package-lock.json
- firestore-bigquery-export/functions/package.json
- firestore-bigquery-export/functions/src/config.ts
- firestore-bigquery-export/functions/src/index.ts
- firestore-bigquery-export/scripts/gen-schema-view/package-lock.json
- firestore-bigquery-export/scripts/import/package-lock.json
fixes: https://github.com/firebase/extensions/issues/1693
> feat: add KMS key management param

- firestore-bigquery-export/PREINSTALL.md
- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
This PR improves the instructions for using KMS with this extension
> docs(firestore-bigquery-export): add instructions for adding KMS role

- firestore-translate-text/extension.yaml
fixes: https://github.com/firebase/extensions/issues/1634
> chore(firestore-translate-text): added ai tag

- .github/workflows/npm_publish_bq_scripts.yml
fixes https://github.com/firebase/extensions/issues/1653
> chore(*): update npm version in bq publish script

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
- firestore-bigquery-export/functions/package-lock.json
- firestore-bigquery-export/functions/package.json
should fix https://github.com/firebase/extensions/issues/1745
> fix(firestore-bigquery-export): serialize timestamps 

- firestore-send-email/CHANGELOG.md
- firestore-send-email/README.md
- firestore-send-email/extension.yaml
- firestore-send-email/functions/src/index.ts
- firestore-send-email/functions/src/logs.ts
fixes https://github.com/firebase/extensions/issues/1785
> fix(firestore-send-email): remove missingDeliveryField error

- storage-resize-images/functions/__tests__/unit/modifyImage.test.ts
- storage-resize-images/functions/jest.config.js
- storage-resize-images/functions/src/resize-image.ts
This will fix https://github.com/firebase/extensions/issues/1732
> fix(storage-resize-images): fix posix issue on windows

- firestore-bigquery-export/PREINSTALL.md
- firestore-bigquery-export/README.md
fixes: https://github.com/firebase/extensions/issues/1023
> docs(firestore-bigquery-export): updated table partitioning guide

- firestore-translate-text/functions/__tests__/unit/translateMultipleBackfill.test.ts
- firestore-translate-text/functions/jest.config.js
- firestore-translate-text/functions/package.json
- firestore-translate-text/functions/src/index.ts
- firestore-translate-text/functions/src/translate/common.ts
- firestore-translate-text/functions/src/translate/index.ts
- firestore-translate-text/functions/src/translate/translateDocument.ts
- firestore-translate-text/functions/src/translate/translateMultiple.ts
- firestore-translate-text/functions/src/translate/translateSingle.ts
fixes https://github.com/firebase/extensions/issues/1737
> fix(firestore-translate-text): handle array input correctly in backfill

- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/functions/src/config.ts
> fix(firestore-bigquery-export): backfill value mismatch

- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/functions/src/index.ts
should fix https://github.com/firebase/extensions/issues/1814
> fix(firestore-bigquery-export): fix collection group query on backfill

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/functions/src/config.ts
rollback of backfill lifecycle event
> Release: firestore-bigquery-export

- storage-resize-images/extension.yaml
> feat(storage-resize-images): add 4 and 8 GB memory options

- .github/workflows/readmes-updated.yml
- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/firestore-bigquery-change-tracker/package-lock.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/partitioning.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/partitioning.ts
- firestore-bigquery-export/functions/package-lock.json
- firestore-bigquery-export/functions/package.json
- firestore-bigquery-export/scripts/import/package-lock.json
- firestore-bigquery-export/scripts/import/package.json
This PR bumps the changetracker and adds the README CI
> release: firestore-bigquery-changetracker

- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
fixes https://github.com/firebase/extensions/issues/1293
> docs(firestore-bigquery-export):update the doc for Partitioning option

- .prettierignore
- auth-mailchimp-sync/extension.yaml
- delete-user-data/extension.yaml
- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
- firestore-counter/extension.yaml
- firestore-send-email/README.md
- firestore-send-email/extension.yaml
- firestore-shorten-urls-bitly/extension.yaml
- firestore-translate-text/extension.yaml
- rtdb-limit-child-nodes/extension.yaml
- samples/rtdb-uppercase-messages/extension.yaml
- storage-resize-images/README.md
- storage-resize-images/extension.yaml
This PR formats all `extension.yaml` files.
> format(*): remove extension.yaml from .prettierignore

- firestore-bigquery-export/POSTINSTALL.md
- firestore-bigquery-export/PREINSTALL.md
- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/functions/src/config.ts
Brings back the backfill feature and updates related docs.
Closes #1890
> feat(firestore-bigquery-export): bring back backfill

- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/partitioning.ts
- Refactored partition validation flow
- Removed redundant and duplicated logs
- Added correct Promise resolution
Should fix #1368 and close PR #1461
> refactor(firebase-bigquery-change-tracker): optimize partitioning validation logic

- storage-resize-images/PREINSTALL.md
- storage-resize-images/README.md
fixes : https://github.com/firebase/extensions/issues/604
> docs(storage-resize-image): add a sample for using events

- firestore-bigquery-export/PREINSTALL.md
- firestore-bigquery-export/README.md
> docs(firestore-bigquery-export): remove mention of bigquery updating on import

- firestore-bigquery-export/scripts/gen-schema-view/src/index.ts
- firestore-bigquery-export/scripts/gen-schema-view/src/schema/index.ts
> feat(firestore-bigquery-export): add `bigquery-project-id` param to `gen-schema-view`

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/firestore-bigquery-change-tracker/package-lock.json
- firestore-bigquery-export/functions/src/index.ts
- firestore-bigquery-export/scripts/gen-schema-view/package-lock.json
- firestore-bigquery-export/scripts/import/package-lock.json
* fix(firestore-bigquery-export): disable onInstall backfill
* chore(firestore-bigquery-export): increment CHANGELOG and version
> release: 26 March 2024

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/functions/src/index.ts
> fix: no resource found for `fsimportexistingdocs`

- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/e2e.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/partitioning.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/utils.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/utils.ts
- firestore-bigquery-export/functions/package-lock.json
- firestore-bigquery-export/functions/package.json
This PR adds a check to see if the table exists (when we check if a partition exists) - fixes https://github.com/firebase/extensions/issues/2048 (needs version bump in ext)
> fix(firestore-bigquery-changetracker): create table fix

- delete-user-data/functions/__tests__/handleDelete.test.ts
- delete-user-data/functions/__tests__/recursiveDelete.test.ts
- delete-user-data/functions/package-lock.json
- delete-user-data/functions/package.json
- delete-user-data/functions/src/index.ts
- delete-user-data/functions/src/recursiveDelete.test.ts
- delete-user-data/functions/src/recursiveDelete.ts
- package-lock.json
- package.json
fixes https://github.com/firebase/extensions/issues/2031
> fix(delete-user-data): recursive delete searched docs if enabled

- firestore-send-email/CHANGELOG.md
- firestore-send-email/extension.yaml
- firestore-send-email/functions/__tests__/helpers.test.ts
- firestore-send-email/functions/src/helpers.ts
- firestore-send-email/functions/src/index.ts
This release is **just** for firestore-send-email
it fixes dependencies and vulnerabilities, as well as a sendgrid fields issue
> release 23/04/24

- auth-mailchimp-sync/CHANGELOG.md
- auth-mailchimp-sync/extension.yaml
- firestore-bigquery-export/firestore-bigquery-change-tracker/package-lock.json
- firestore-bigquery-export/functions/package-lock.json
- firestore-bigquery-export/scripts/gen-schema-view/package-lock.json
- firestore-bigquery-export/scripts/gen-schema-view/package.json
- firestore-counter/CHANGELOG.md
- firestore-counter/extension.yaml
- firestore-send-email/functions/package-lock.json
- firestore-shorten-urls-bitly/CHANGELOG.md
- firestore-translate-text/CHANGELOG.md
- firestore-translate-text/extension.yaml
- rtdb-limit-child-nodes/CHANGELOG.md
- rtdb-limit-child-nodes/extension.yaml
This PR bumps extension versions for all that still require the vulnerability fix
> chore(*): bump changelogs

- firestore-bigquery-export/firestore-bigquery-change-tracker/package-lock.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/alternativeProject.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/checkUpdates.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/clustering.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/e2e.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/partitioning.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/stresstest.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/wildcardDocument.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/queries.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/partitioning.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/tsconfig.test.json
- firestore-bigquery-export/functions/__tests__/e2e.test.ts
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/e2e/e2e.test.ts
fixes: https://github.com/firebase/extensions/issues/2091
> fix(firestore-bigquery-export): fixed timestamp as a field-name partitioning

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/functions/src/config.ts
should fix https://github.com/firebase/extensions/issues/2090
> fix(firestore-bigquery-export): remove multiple database support

- firestore-bigquery-export/extension.yaml
- firestore-send-email/functions/__tests__/e2e.test.ts
This test is broken and stopping the release. We should introduce the smart CI.
> chore(firestore-send-email): disable broken test

- firestore-bigquery-export/firestore-bigquery-change-tracker/package-lock.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
This PR is running npm audit fix on changetracker and bumping the version
> fix(firestore-bigquery-changetracker): run npm audit fix

- firestore-bigquery-export/firestore-bigquery-change-tracker/package-lock.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
This PR fixes vulnerabilities with the change tracker package
> fix(firestore-bigquery-change-tracker): fix vulnerabilities

- firestore-translate-text/CHANGELOG.md
- firestore-translate-text/extension.yaml
- firestore-translate-text/functions/package-lock.json
This PR fixes vulnerabilities in dependencies
> fix(firestore-translate-text): fix vulnerabilities

- storage-resize-images/CHANGELOG.md
- storage-resize-images/extension.yaml
- storage-resize-images/functions/package-lock.json
This PR fixes vulnerabilities in dependencies
> fix(storage-resize-images): fix vulnerabilities

- rtdb-limit-child-nodes/CHANGELOG.md
- rtdb-limit-child-nodes/extension.yaml
- rtdb-limit-child-nodes/functions/package-lock.json
This PR fixes vulnerabilities in dependencies
> fix(rtdb-limit-child-nodes): fix vulnerabilities

- delete-user-data/CHANGELOG.md
- delete-user-data/extension.yaml
- delete-user-data/functions/package-lock.json
This PR fixes vulnerabilities in dependencies
> fix(delete-user-data): fix vulnerabilities

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/functions/package-lock.json
- firestore-bigquery-export/functions/package.json
- firestore-bigquery-export/scripts/gen-schema-view/package-lock.json
- firestore-bigquery-export/scripts/gen-schema-view/package.json
- firestore-bigquery-export/scripts/import/__tests__/e2e.test.ts
- firestore-bigquery-export/scripts/import/package-lock.json
- firestore-bigquery-export/scripts/import/package.json
This PR bumps deps in the BQ scripts and extensions to remove vulnerabilities
Do not merge until https://github.com/firebase/extensions/pull/2151 is merged and released (DONE)
> fix(firestore-bigquery-export): fix vulnerabilities with extension and script

- firestore-shorten-urls-bitly/CHANGELOG.md
- firestore-shorten-urls-bitly/extension.yaml
- firestore-shorten-urls-bitly/functions/package-lock.json
- firestore-shorten-urls-bitly/functions/package.json
- firestore-shorten-urls-bitly/functions/src/index.ts
This PR removes the axios dependency which is unnecessary and causes vulnerabilities sometimes (e.g now)
> fix(firestore-shorten-urls-bitly): fix vulnerabilities

- firestore-bigquery-export/firestore-bigquery-change-tracker/package-lock.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
This PR bumps deps to fix vulnerabilities
> fix(change-tracker): npm audit fix

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/functions/__tests__/__snapshots__/config.test.ts.snap
- firestore-bigquery-export/functions/src/config.ts
- firestore-bigquery-export/functions/src/index.ts
- firestore-bigquery-export/functions/src/logs.ts
This PR adds logging of data that failed to queue
> fix: add logging of failed export data

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
- firestore-bigquery-export/functions/__tests__/__snapshots__/config.test.ts.snap
- firestore-bigquery-export/functions/src/config.ts
- firestore-bigquery-export/functions/src/index.ts
- firestore-bigquery-export/functions/src/logs.ts
Reverts firebase/extensions#2180
> Revert "fix: add logging of failed export data"

- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/tsconfig.json
- firestore-bigquery-export/functions/package-lock.json
- firestore-bigquery-export/functions/src/index.ts
- firestore-bigquery-export/scripts/gen-schema-view/package-lock.json
- firestore-bigquery-export/scripts/import/package-lock.json
- firestore-bigquery-export/scripts/import/src/helper.ts
- firestore-bigquery-export/scripts/import/src/index.ts
- firestore-bigquery-export/scripts/import/src/worker.ts
This PR makes the types available when using the change tracker. It also fixes these types where they're being used.
> feat(firestore-bigquery-changetracker): include .d.ts files

- firestore-translate-text/CHANGELOG.md
- firestore-translate-text/PREINSTALL.md
- firestore-translate-text/README.md
- firestore-translate-text/extension.yaml
- firestore-translate-text/functions/package-lock.json
- firestore-translate-text/functions/package.json
- firestore-translate-text/functions/src/config.ts
- firestore-translate-text/functions/src/translate/common.ts
- firestore-translate-text/functions/tsconfig.json
This PR adds the optional feature of using Gemini 1.5 Pro for translations, powered by Firebase Genkit.
> feat(firestore-translate-text): optionally allow genkit for translations

- firestore-bigquery-export/firestore-bigquery-change-tracker/package-lock.json
- firestore-bigquery-export/scripts/gen-schema-view/package.json
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/schema-loader-utils/schema-loader-utils.test.ts
- firestore-bigquery-export/scripts/gen-schema-view/src/index.ts
- firestore-bigquery-export/scripts/gen-schema-view/src/schema-loader-utils.ts
- firestore-translate-text/CHANGELOG.md
- firestore-translate-text/PREINSTALL.md
- firestore-translate-text/README.md
- firestore-translate-text/extension.yaml
- firestore-translate-text/functions/package-lock.json
- firestore-translate-text/functions/package.json
- firestore-translate-text/functions/src/config.ts
- firestore-translate-text/functions/src/translate/common.ts
- firestore-translate-text/functions/tsconfig.json
- package-lock.json
This PR is to release the translate text extension
> release: 10/12/2024

- firestore-translate-text/CHANGELOG.md
- firestore-translate-text/PREINSTALL.md
- firestore-translate-text/README.md
- firestore-translate-text/extension.yaml
- firestore-translate-text/functions/src/config.ts
- firestore-translate-text/functions/src/translate/common.ts
> feat(firestore-translate-text): improve config and docs on AI Translations

- firestore-bigquery-export/firestore-bigquery-change-tracker/jest.config.js
- firestore-bigquery-export/firestore-bigquery-change-tracker/package-lock.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/alternativeProject.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/checkUpdates.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/clustering.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/e2e.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/stresstest.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/wildcardDocument.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/changeTracker.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/clearTables.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/clustering.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/logs.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/tsconfig.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/tsconfig.test.json
changetracker PR to fix https://github.com/firebase/extensions/issues/2134
> fix(firestore-bigquery-changetracker): do not cluster invalid types

- firestore-bigquery-export/firestore-bigquery-change-tracker/jest.config.js
- firestore-bigquery-export/firestore-bigquery-change-tracker/package-lock.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/alternativeProject.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/checkUpdates.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/clustering.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/e2e.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/materializedViews/initializeLatestMaterializedView.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/materializedViews/initializeLatestView.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/materializedViews/integration.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/materializedViews/shouldRecreateMaterializedView.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/msql/incremental/standard.sql
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/msql/nonIncremental/standard.sql
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/snapshot.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/stresstest.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/bigquery/wildcardDocument.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/changeTracker.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/clearTables.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/sql/latestConsistentSnapshot.sql
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/sql/latestConsistentSnapshotNoGroupBy.sql
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/initializeLatestMaterializedView.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/initializeLatestView.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/snapshot.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/utils.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/tsconfig.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/tsconfig.test.json
This PR adds a materialized views feature to the change tracker.
fixes https://github.com/firebase/extensions/issues/746
> feat(bq-change-tracker): materialized views

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/POSTINSTALL.md
- firestore-bigquery-export/scripts/grant-crossproject-access.ps1
- firestore-bigquery-export/scripts/grant-crossproject-access.sh
fixes https://github.com/firebase/extensions/issues/1962
> docs(firestore-bigquery-export): improve cross-project IAM docs

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/PREINSTALL.md
- firestore-bigquery-export/README.md
resolves https://github.com/firebase/extensions/issues/2135
> docs(firestore-bigquery-export): add docs on reconfig workaround

- firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md
- firestore-bigquery-export/scripts/import/package-lock.json
- firestore-bigquery-export/scripts/import/src/config.ts
- firestore-bigquery-export/scripts/import/src/index.ts
- firestore-bigquery-export/scripts/import/src/program.ts
- firestore-bigquery-export/scripts/import/src/types.ts
- firestore-bigquery-export/scripts/import/src/worker.ts
Should resolve https://github.com/firebase/extensions/issues/2142
> feat(fs-bq-import-collection): add transformFunction option

- firestore-send-email/CHANGELOG.md
- firestore-send-email/POSTINSTALL.md
- firestore-send-email/PREINSTALL.md
- firestore-send-email/README.md
fixes https://github.com/firebase/extensions/issues/1946
> docs(firestore-send-email): add docs for ttl setup

- storage-resize-images/CHANGELOG.md
- storage-resize-images/extension.yaml
- storage-resize-images/functions/__tests__/util.test.ts
- storage-resize-images/functions/src/util.ts
> feat(storage-resize-images): support '+' character in path

- storage-resize-images/CHANGELOG.md
- storage-resize-images/PREINSTALL.md
- storage-resize-images/README.md
fixes https://github.com/firebase/extensions/issues/2089
> docs(storage-resize-images): fix typo in PREINSTALL

- storage-resize-images/CHANGELOG.md
- storage-resize-images/functions/__tests__/util.test.ts
- storage-resize-images/functions/src/filters.ts
- storage-resize-images/functions/src/resize-image.ts
- storage-resize-images/functions/src/util.ts
> fix(storage-resize-images): windows path fixed

- firestore-translate-text/CHANGELOG.md
- firestore-translate-text/README.md
- firestore-translate-text/extension.yaml
> fix: disable backfill on translate text

- firestore-bigquery-export/CHANGELOG.md
- firestore-bigquery-export/README.md
- firestore-bigquery-export/extension.yaml
fixes https://github.com/firebase/extensions/issues/2084
> docs(firestore-bigquery-export): fix small typo in max dispatches param

- firestore-bigquery-export/firestore-bigquery-change-tracker/package.json
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/fixtures/changeTracker.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/__tests__/logger.test.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/index.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/logger.ts
- firestore-bigquery-export/firestore-bigquery-change-tracker/src/logs.ts
This PR adds a custom Logger class to the changetracker packages
> feat(fs-bq-change-tracker): add logger with log levels

- firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md
This PR adds a reference to the gen-schema-view script in the import script guide
> docs(fs-bq-import-collection): add reference to gen-schema-view guide

- .github/workflows/npm_publish_bq_scripts.yml
- .github/workflows/readmes-updated.yml
- .github/workflows/test.yml
- .github/workflows/validate.yml
This PR bumps node versions in the workflows
> chore: bump to node 20 in workflows

- firestore-shorten-urls-bitly/POSTINSTALL.md
- firestore-shorten-urls-bitly/README.md
- firestore-shorten-urls-bitly/extension.yaml
- firestore-shorten-urls-bitly/functions/package-lock.json
- firestore-shorten-urls-bitly/functions/src/config.ts
This PR fixes an issue where v2 functions have the wrong location as their trigger
> fix(firestore-shorten-urls-bitly): add database location param

- firestore-bigquery-export/functions/src/index.ts
This PR cleans up code comments in the bigquery export file
> chore(firestore-bigquery-export): clean up code comments

- firestore-send-email/CHANGELOG.md
- firestore-send-email/functions/__tests__/validation.test.ts
- firestore-send-email/functions/package-lock.json
- firestore-send-email/functions/package.json
- firestore-send-email/functions/src/index.ts
- firestore-send-email/functions/src/validation.ts
fixes https://github.com/firebase/extensions/issues/2392
> fix(firestore-send-email): improve validation of firestore objects

- firestore-bigquery-export/scripts/import/src/index.ts
- firestore-bigquery-export/scripts/import/src/run-single-thread.ts
This PR resolves https://github.com/firebase/extensions/issues/2407 and also adds additional handling for when the collection cannot be found.
Also fixes https://github.com/firebase/extensions/issues/2406
> fix(import-script): await runSingleThread

- firestore-bigquery-export/scripts/gen-schema-view/package.json
- firestore-bigquery-export/scripts/import/package.json
This PR bumps the versions in these scripts ready for release
> chore(firestore-bigquery-export): bump script versions for release

- firestore-send-email/functions/__tests__/validation.test.ts
- firestore-send-email/functions/src/validation.ts
fixes https://github.com/firebase/extensions/issues/2419
> fix(firestore-send-email): fix validation logic

- firestore-translate-text/PREINSTALL.md
- firestore-translate-text/README.md
> docs(firestore-translate-text): add genkit.dev reference to docs

- storage-resize-images/PREINSTALL.md
- storage-resize-images/README.md
Fixes https://github.com/firebase/extensions/issues/2461
> docs(storage-resize-images): add genkit.dev reference to docs

- firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md
- firestore-bigquery-export/scripts/gen-schema-view/package-lock.json
- firestore-bigquery-export/scripts/gen-schema-view/package.json
- firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/genkit/sampleFirestoreDocuments.test.ts
- firestore-bigquery-export/scripts/gen-schema-view/src/schema/genkit.ts
> chore(firestore-bigquery-export/gen-schema-view): update gemini to 2.5

- firestore-translate-text/CHANGELOG.md
- firestore-translate-text/extension.yaml
- firestore-translate-text/functions/package-lock.json
- firestore-translate-text/functions/package.json
Resolves https://github.com/firebase/extensions/issues/2495
> feat(firestore-translate-text): add Gemini 2.5 Flash Lite
